# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from FinamPy.proto.tradeapi.v1 import events_pb2 as proto_dot_tradeapi_dot_v1_dot_events__pb2


class EventsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetEvents = channel.stream_stream(
                '/grpc.tradeapi.v1.Events/GetEvents',
                request_serializer=proto_dot_tradeapi_dot_v1_dot_events__pb2.SubscriptionRequest.SerializeToString,
                response_deserializer=proto_dot_tradeapi_dot_v1_dot_events__pb2.Event.FromString,
                )


class EventsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetEvents(self, request_iterator, context):
        """Event Service sends events after explicit subscription.
        Сервис событий. Отправляет события после вызова соответствующих методов подписки.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetEvents': grpc.stream_stream_rpc_method_handler(
                    servicer.GetEvents,
                    request_deserializer=proto_dot_tradeapi_dot_v1_dot_events__pb2.SubscriptionRequest.FromString,
                    response_serializer=proto_dot_tradeapi_dot_v1_dot_events__pb2.Event.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.tradeapi.v1.Events', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Events(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetEvents(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/grpc.tradeapi.v1.Events/GetEvents',
            proto_dot_tradeapi_dot_v1_dot_events__pb2.SubscriptionRequest.SerializeToString,
            proto_dot_tradeapi_dot_v1_dot_events__pb2.Event.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
