# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc/tradeapi/v1/orders.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from FinamPy.proto.tradeapi.v1 import orders_pb2 as proto_dot_tradeapi_dot_v1_dot_orders__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dgrpc/tradeapi/v1/orders.proto\x12\x10grpc.tradeapi.v1\x1a\x1eproto/tradeapi/v1/orders.proto2\x8d\x02\n\x06Orders\x12Q\n\x08NewOrder\x12\".proto.tradeapi.v1.NewOrderRequest\x1a!.proto.tradeapi.v1.NewOrderResult\x12Z\n\x0b\x43\x61ncelOrder\x12%.proto.tradeapi.v1.CancelOrderRequest\x1a$.proto.tradeapi.v1.CancelOrderResult\x12T\n\tGetOrders\x12#.proto.tradeapi.v1.GetOrdersRequest\x1a\".proto.tradeapi.v1.GetOrdersResultB\x19\xaa\x02\x16\x46inam.TradeApi.Grpc.V1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc.tradeapi.v1.orders_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\026Finam.TradeApi.Grpc.V1'
  _ORDERS._serialized_start=84
  _ORDERS._serialized_end=353
# @@protoc_insertion_point(module_scope)
