# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc/tradeapi/v1/portfolios.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.tradeapi.v1 import portfolios_pb2 as proto_dot_tradeapi_dot_v1_dot_portfolios__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!grpc/tradeapi/v1/portfolios.proto\x12\x10grpc.tradeapi.v1\x1a\"proto/tradeapi/v1/portfolios.proto2k\n\nPortfolios\x12]\n\x0cGetPortfolio\x12&.proto.tradeapi.v1.GetPortfolioRequest\x1a%.proto.tradeapi.v1.GetPortfolioResultB\x19\xaa\x02\x16\x46inam.TradeApi.Grpc.V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc.tradeapi.v1.portfolios_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\026Finam.TradeApi.Grpc.V1'
  _globals['_PORTFOLIOS']._serialized_start=91
  _globals['_PORTFOLIOS']._serialized_end=198
# @@protoc_insertion_point(module_scope)
