"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import proto.tradeapi.v1.security_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class GetSecuritiesRequest(google.protobuf.message.Message):
    """Securities list request.
    Запрос списка инструментов.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___GetSecuritiesRequest = GetSecuritiesRequest

@typing_extensions.final
class GetSecuritiesResult(google.protobuf.message.Message):
    """Result of get security lists request.
    Результат выполнения запроса списка инструментов.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SECURITIES_FIELD_NUMBER: builtins.int
    @property
    def securities(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[proto.tradeapi.v1.security_pb2.Security]:
        """Securities list.
        Список инструментов.
        """
    def __init__(
        self,
        *,
        securities: collections.abc.Iterable[proto.tradeapi.v1.security_pb2.Security] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["securities", b"securities"]) -> None: ...

global___GetSecuritiesResult = GetSecuritiesResult
