"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import FinamPy.proto_old.security_pb2
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.wrappers_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GetSecuritiesRequest(google.protobuf.message.Message):
    """Securities list request.
    Запрос списка инструментов.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BOARD_FIELD_NUMBER: builtins.int
    SECCODE_FIELD_NUMBER: builtins.int
    @property
    def board(self) -> google.protobuf.wrappers_pb2.StringValue:
        """Trading Board.
        Режим торгов
        """

    @property
    def seccode(self) -> google.protobuf.wrappers_pb2.StringValue:
        """Security Code.
        Тикер инструмента.
        """

    def __init__(
        self,
        *,
        board: google.protobuf.wrappers_pb2.StringValue | None = ...,
        seccode: google.protobuf.wrappers_pb2.StringValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["board", b"board", "seccode", b"seccode"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["board", b"board", "seccode", b"seccode"]) -> None: ...

global___GetSecuritiesRequest = GetSecuritiesRequest

@typing.final
class GetSecuritiesResult(google.protobuf.message.Message):
    """Result of get security lists request.
    Результат выполнения запроса списка инструментов.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SECURITIES_FIELD_NUMBER: builtins.int
    @property
    def securities(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[FinamPy.proto_old.security_pb2.Security]:
        """Securities list.
        Список инструментов.
        """

    def __init__(
        self,
        *,
        securities: collections.abc.Iterable[FinamPy.proto_old.security_pb2.Security] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["securities", b"securities"]) -> None: ...

global___GetSecuritiesResult = GetSecuritiesResult
