# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: FinamPy/FinamPy/grpc/metrics/usage_metrics_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'FinamPy/FinamPy/grpc/metrics/usage_metrics_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8FinamPy/FinamPy/grpc/metrics/usage_metrics_service.proto\x12\x18grpc.tradeapi.v1.metrics\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x18\n\x16GetUsageMetricsRequest\"\xd5\x01\n\x17GetUsageMetricsResponse\x12L\n\x06quotas\x18\x01 \x03(\x0b\x32<.grpc.tradeapi.v1.metrics.GetUsageMetricsResponse.QuotaUsage\x1al\n\nQuotaUsage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x03\x12\x11\n\tremaining\x18\x03 \x01(\x03\x12.\n\nreset_time\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\xa1\x01\n\x13UsageMetricsService\x12\x89\x01\n\x0fGetUsageMetrics\x12\x30.grpc.tradeapi.v1.metrics.GetUsageMetricsRequest\x1a\x31.grpc.tradeapi.v1.metrics.GetUsageMetricsResponse\"\x11\x82\xd3\xe4\x93\x02\x0b\x12\t/v1/usageB.P\x01Z*trade_api/v1/metrics/usage_metrics_serviceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FinamPy.FinamPy.grpc.metrics.usage_metrics_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001Z*trade_api/v1/metrics/usage_metrics_service'
  _globals['_USAGEMETRICSSERVICE'].methods_by_name['GetUsageMetrics']._loaded_options = None
  _globals['_USAGEMETRICSSERVICE'].methods_by_name['GetUsageMetrics']._serialized_options = b'\202\323\344\223\002\013\022\t/v1/usage'
  _globals['_GETUSAGEMETRICSREQUEST']._serialized_start=149
  _globals['_GETUSAGEMETRICSREQUEST']._serialized_end=173
  _globals['_GETUSAGEMETRICSRESPONSE']._serialized_start=176
  _globals['_GETUSAGEMETRICSRESPONSE']._serialized_end=389
  _globals['_GETUSAGEMETRICSRESPONSE_QUOTAUSAGE']._serialized_start=281
  _globals['_GETUSAGEMETRICSRESPONSE_QUOTAUSAGE']._serialized_end=389
  _globals['_USAGEMETRICSSERVICE']._serialized_start=392
  _globals['_USAGEMETRICSSERVICE']._serialized_end=553
# @@protoc_insertion_point(module_scope)
