"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.type.date_pb2
import google.type.decimal_pb2
import google.type.interval_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ExchangesRequest(google.protobuf.message.Message):
    """Запрос получения списка доступных бирж"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___ExchangesRequest = ExchangesRequest

@typing.final
class ExchangesResponse(google.protobuf.message.Message):
    """Список доступных бирж"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EXCHANGES_FIELD_NUMBER: builtins.int
    @property
    def exchanges(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Exchange]:
        """Информация о бирже"""

    def __init__(
        self,
        *,
        exchanges: collections.abc.Iterable[global___Exchange] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["exchanges", b"exchanges"]) -> None: ...

global___ExchangesResponse = ExchangesResponse

@typing.final
class AssetsRequest(google.protobuf.message.Message):
    """Запрос получения списка доступных инструментов"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___AssetsRequest = AssetsRequest

@typing.final
class AssetsResponse(google.protobuf.message.Message):
    """Список доступных инструментов"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ASSETS_FIELD_NUMBER: builtins.int
    @property
    def assets(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Asset]:
        """Информация об инструменте"""

    def __init__(
        self,
        *,
        assets: collections.abc.Iterable[global___Asset] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["assets", b"assets"]) -> None: ...

global___AssetsResponse = AssetsResponse

@typing.final
class OptionsChainRequest(google.protobuf.message.Message):
    """Запрос получения цепочки опционов"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UNDERLYING_SYMBOL_FIELD_NUMBER: builtins.int
    underlying_symbol: builtins.str
    """Символ базового актива опциона"""
    def __init__(
        self,
        *,
        underlying_symbol: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["underlying_symbol", b"underlying_symbol"]) -> None: ...

global___OptionsChainRequest = OptionsChainRequest

@typing.final
class OptionsChainResponse(google.protobuf.message.Message):
    """Информация о цепочке опционов"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: builtins.int
    OPTIONS_FIELD_NUMBER: builtins.int
    symbol: builtins.str
    """Символ опциона"""
    @property
    def options(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Option]:
        """Информация об опционе"""

    def __init__(
        self,
        *,
        symbol: builtins.str = ...,
        options: collections.abc.Iterable[global___Option] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["options", b"options", "symbol", b"symbol"]) -> None: ...

global___OptionsChainResponse = OptionsChainResponse

@typing.final
class ScheduleRequest(google.protobuf.message.Message):
    """Запрос получения расписания инструмента"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: builtins.int
    symbol: builtins.str
    """Символ инструмента"""
    def __init__(
        self,
        *,
        symbol: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["symbol", b"symbol"]) -> None: ...

global___ScheduleRequest = ScheduleRequest

@typing.final
class ScheduleResponse(google.protobuf.message.Message):
    """Расписание инструмента"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class Sessions(google.protobuf.message.Message):
        """Сессии"""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        TYPE_FIELD_NUMBER: builtins.int
        INTERVAL_FIELD_NUMBER: builtins.int
        type: builtins.str
        """Тип сессии"""
        @property
        def interval(self) -> google.type.interval_pb2.Interval:
            """Интервал сессии"""

        def __init__(
            self,
            *,
            type: builtins.str = ...,
            interval: google.type.interval_pb2.Interval | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["interval", b"interval"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["interval", b"interval", "type", b"type"]) -> None: ...

    SYMBOL_FIELD_NUMBER: builtins.int
    SESSIONS_FIELD_NUMBER: builtins.int
    symbol: builtins.str
    """Символ инструмента"""
    @property
    def sessions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ScheduleResponse.Sessions]:
        """Сессии инструмента"""

    def __init__(
        self,
        *,
        symbol: builtins.str = ...,
        sessions: collections.abc.Iterable[global___ScheduleResponse.Sessions] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["sessions", b"sessions", "symbol", b"symbol"]) -> None: ...

global___ScheduleResponse = ScheduleResponse

@typing.final
class Exchange(google.protobuf.message.Message):
    """Информация о бирже"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MIC_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    mic: builtins.str
    """Идентификатор биржи mic"""
    name: builtins.str
    """Наименование биржи"""
    def __init__(
        self,
        *,
        mic: builtins.str = ...,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["mic", b"mic", "name", b"name"]) -> None: ...

global___Exchange = Exchange

@typing.final
class Asset(google.protobuf.message.Message):
    """Информация об инструменте"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    TICKER_FIELD_NUMBER: builtins.int
    MIC_FIELD_NUMBER: builtins.int
    ISIN_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    symbol: builtins.str
    """Символ инструмента ticker@mic"""
    id: builtins.str
    """Идентификатор инструмента"""
    ticker: builtins.str
    """Тикер инструмента"""
    mic: builtins.str
    """mic идентификатор биржи"""
    isin: builtins.str
    """Isin идентификатор инструмента"""
    type: builtins.str
    """Тип инструмента"""
    name: builtins.str
    """Наименование инструмента"""
    def __init__(
        self,
        *,
        symbol: builtins.str = ...,
        id: builtins.str = ...,
        ticker: builtins.str = ...,
        mic: builtins.str = ...,
        isin: builtins.str = ...,
        type: builtins.str = ...,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id", "isin", b"isin", "mic", b"mic", "name", b"name", "symbol", b"symbol", "ticker", b"ticker", "type", b"type"]) -> None: ...

global___Asset = Asset

@typing.final
class Option(google.protobuf.message.Message):
    """Инфомация об опционе"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Type:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _TypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Option._Type.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        TYPE_UNSPECIFIED: Option._Type.ValueType  # 0
        """Неопределенное значение"""
        TYPE_CALL: Option._Type.ValueType  # 1
        """Колл"""
        TYPE_PUT: Option._Type.ValueType  # 2
        """Пут"""

    class Type(_Type, metaclass=_TypeEnumTypeWrapper):
        """Тип опциона"""

    TYPE_UNSPECIFIED: Option.Type.ValueType  # 0
    """Неопределенное значение"""
    TYPE_CALL: Option.Type.ValueType  # 1
    """Колл"""
    TYPE_PUT: Option.Type.ValueType  # 2
    """Пут"""

    SYMBOL_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    CONTRACT_SIZE_FIELD_NUMBER: builtins.int
    TRADE_FIRST_DAY_FIELD_NUMBER: builtins.int
    TRADE_LAST_DAY_FIELD_NUMBER: builtins.int
    STRIKE_FIELD_NUMBER: builtins.int
    MULTIPLIER_FIELD_NUMBER: builtins.int
    symbol: builtins.str
    """Символ инструмента"""
    type: global___Option.Type.ValueType
    """Тип инструмента"""
    @property
    def contract_size(self) -> google.type.decimal_pb2.Decimal:
        """Лот, количество базового актива в инструменте"""

    @property
    def trade_first_day(self) -> google.type.date_pb2.Date:
        """Дата начала торговли"""

    @property
    def trade_last_day(self) -> google.type.date_pb2.Date:
        """Дата экспирации"""

    @property
    def strike(self) -> google.type.decimal_pb2.Decimal:
        """Цена исполнения опциона"""

    @property
    def multiplier(self) -> google.type.decimal_pb2.Decimal:
        """Множитель опциона"""

    def __init__(
        self,
        *,
        symbol: builtins.str = ...,
        type: global___Option.Type.ValueType = ...,
        contract_size: google.type.decimal_pb2.Decimal | None = ...,
        trade_first_day: google.type.date_pb2.Date | None = ...,
        trade_last_day: google.type.date_pb2.Date | None = ...,
        strike: google.type.decimal_pb2.Decimal | None = ...,
        multiplier: google.type.decimal_pb2.Decimal | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["contract_size", b"contract_size", "multiplier", b"multiplier", "strike", b"strike", "trade_first_day", b"trade_first_day", "trade_last_day", b"trade_last_day"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["contract_size", b"contract_size", "multiplier", b"multiplier", "strike", b"strike", "symbol", b"symbol", "trade_first_day", b"trade_first_day", "trade_last_day", b"trade_last_day", "type", b"type"]) -> None: ...

global___Option = Option
