"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import struct_pb2 as _struct_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _Scheme:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _SchemeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_Scheme.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    UNKNOWN: _Scheme.ValueType  # 0
    HTTP: _Scheme.ValueType  # 1
    HTTPS: _Scheme.ValueType  # 2
    WS: _Scheme.ValueType  # 3
    WSS: _Scheme.ValueType  # 4

class Scheme(_Scheme, metaclass=_SchemeEnumTypeWrapper):
    """Scheme describes the schemes supported by the OpenAPI Swagger
    and Operation objects.
    """

UNKNOWN: Scheme.ValueType  # 0
HTTP: Scheme.ValueType  # 1
HTTPS: Scheme.ValueType  # 2
WS: Scheme.ValueType  # 3
WSS: Scheme.ValueType  # 4
Global___Scheme: _TypeAlias = Scheme  # noqa: Y015

@_typing.final
class Swagger(_message.Message):
    """`Swagger` is a representation of OpenAPI v2 specification's Swagger object.

    See: https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#swaggerObject

    Example:

     option (protoc_gen_openapiv2.options.openapiv2_swagger) = {
       info: {
         title: "Echo API";
         version: "1.0";
         description: "";
         contact: {
           name: "gRPC-Gateway project";
           url: "https://github.com/grpc-ecosystem/grpc-gateway";
           email: "none@example.com";
         };
         license: {
           name: "BSD 3-Clause License";
           url: "https://github.com/grpc-ecosystem/grpc-gateway/blob/main/LICENSE";
         };
       };
       schemes: HTTPS;
       consumes: "application/json";
       produces: "application/json";
     };
    """

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class ResponsesEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> Global___Response: ...
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: Global___Response | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class ExtensionsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> _struct_pb2.Value: ...
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _struct_pb2.Value | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    SWAGGER_FIELD_NUMBER: _builtins.int
    INFO_FIELD_NUMBER: _builtins.int
    HOST_FIELD_NUMBER: _builtins.int
    BASE_PATH_FIELD_NUMBER: _builtins.int
    SCHEMES_FIELD_NUMBER: _builtins.int
    CONSUMES_FIELD_NUMBER: _builtins.int
    PRODUCES_FIELD_NUMBER: _builtins.int
    RESPONSES_FIELD_NUMBER: _builtins.int
    SECURITY_DEFINITIONS_FIELD_NUMBER: _builtins.int
    SECURITY_FIELD_NUMBER: _builtins.int
    TAGS_FIELD_NUMBER: _builtins.int
    EXTERNAL_DOCS_FIELD_NUMBER: _builtins.int
    EXTENSIONS_FIELD_NUMBER: _builtins.int
    swagger: _builtins.str
    """Specifies the OpenAPI Specification version being used. It can be
    used by the OpenAPI UI and other clients to interpret the API listing. The
    value MUST be "2.0".
    """
    host: _builtins.str
    """The host (name or ip) serving the API. This MUST be the host only and does
    not include the scheme nor sub-paths. It MAY include a port. If the host is
    not included, the host serving the documentation is to be used (including
    the port). The host does not support path templating.
    """
    base_path: _builtins.str
    """The base path on which the API is served, which is relative to the host. If
    it is not included, the API is served directly under the host. The value
    MUST start with a leading slash (/). The basePath does not support path
    templating.
    Note that using `base_path` does not change the endpoint paths that are
    generated in the resulting OpenAPI file. If you wish to use `base_path`
    with relatively generated OpenAPI paths, the `base_path` prefix must be
    manually removed from your `google.api.http` paths and your code changed to
    serve the API from the `base_path`.
    """
    @_builtins.property
    def info(self) -> Global___Info:
        """Provides metadata about the API. The metadata can be used by the
        clients if needed.
        """

    @_builtins.property
    def schemes(self) -> _containers.RepeatedScalarFieldContainer[Global___Scheme.ValueType]:
        """The transfer protocol of the API. Values MUST be from the list: "http",
        "https", "ws", "wss". If the schemes is not included, the default scheme to
        be used is the one used to access the OpenAPI definition itself.
        """

    @_builtins.property
    def consumes(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """A list of MIME types the APIs can consume. This is global to all APIs but
        can be overridden on specific API calls. Value MUST be as described under
        Mime Types.
        """

    @_builtins.property
    def produces(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """A list of MIME types the APIs can produce. This is global to all APIs but
        can be overridden on specific API calls. Value MUST be as described under
        Mime Types.
        """

    @_builtins.property
    def responses(self) -> _containers.MessageMap[_builtins.str, Global___Response]:
        """An object to hold responses that can be used across operations. This
        property does not define global responses for all operations.
        """

    @_builtins.property
    def security_definitions(self) -> Global___SecurityDefinitions:
        """Security scheme definitions that can be used across the specification."""

    @_builtins.property
    def security(self) -> _containers.RepeatedCompositeFieldContainer[Global___SecurityRequirement]:
        """A declaration of which security schemes are applied for the API as a whole.
        The list of values describes alternative security schemes that can be used
        (that is, there is a logical OR between the security requirements).
        Individual operations can override this definition.
        """

    @_builtins.property
    def tags(self) -> _containers.RepeatedCompositeFieldContainer[Global___Tag]:
        """A list of tags for API documentation control. Tags can be used for logical
        grouping of operations by resources or any other qualifier.
        """

    @_builtins.property
    def external_docs(self) -> Global___ExternalDocumentation:
        """Additional external documentation."""

    @_builtins.property
    def extensions(self) -> _containers.MessageMap[_builtins.str, _struct_pb2.Value]:
        """Custom properties that start with "x-" such as "x-foo" used to describe
        extra functionality that is not covered by the standard OpenAPI Specification.
        See: https://swagger.io/docs/specification/2-0/swagger-extensions/
        """

    def __init__(
        self,
        *,
        swagger: _builtins.str = ...,
        info: Global___Info | None = ...,
        host: _builtins.str = ...,
        base_path: _builtins.str = ...,
        schemes: _abc.Iterable[Global___Scheme.ValueType] | None = ...,
        consumes: _abc.Iterable[_builtins.str] | None = ...,
        produces: _abc.Iterable[_builtins.str] | None = ...,
        responses: _abc.Mapping[_builtins.str, Global___Response] | None = ...,
        security_definitions: Global___SecurityDefinitions | None = ...,
        security: _abc.Iterable[Global___SecurityRequirement] | None = ...,
        tags: _abc.Iterable[Global___Tag] | None = ...,
        external_docs: Global___ExternalDocumentation | None = ...,
        extensions: _abc.Mapping[_builtins.str, _struct_pb2.Value] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["external_docs", b"external_docs", "info", b"info", "security_definitions", b"security_definitions"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["base_path", b"base_path", "consumes", b"consumes", "extensions", b"extensions", "external_docs", b"external_docs", "host", b"host", "info", b"info", "produces", b"produces", "responses", b"responses", "schemes", b"schemes", "security", b"security", "security_definitions", b"security_definitions", "swagger", b"swagger", "tags", b"tags"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Swagger: _TypeAlias = Swagger  # noqa: Y015

@_typing.final
class Operation(_message.Message):
    """`Operation` is a representation of OpenAPI v2 specification's Operation object.

    See: https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#operationObject

    Example:

     service EchoService {
       rpc Echo(SimpleMessage) returns (SimpleMessage) {
         option (google.api.http) = {
           get: "/v1/example/echo/{id}"
         };

         option (protoc_gen_openapiv2.options.openapiv2_operation) = {
           summary: "Get a message.";
           operation_id: "getMessage";
           tags: "echo";
           responses: {
             key: "200"
               value: {
               description: "OK";
             }
           }
         };
       }
     }
    """

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class ResponsesEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> Global___Response: ...
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: Global___Response | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class ExtensionsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> _struct_pb2.Value: ...
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _struct_pb2.Value | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    TAGS_FIELD_NUMBER: _builtins.int
    SUMMARY_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    EXTERNAL_DOCS_FIELD_NUMBER: _builtins.int
    OPERATION_ID_FIELD_NUMBER: _builtins.int
    CONSUMES_FIELD_NUMBER: _builtins.int
    PRODUCES_FIELD_NUMBER: _builtins.int
    RESPONSES_FIELD_NUMBER: _builtins.int
    SCHEMES_FIELD_NUMBER: _builtins.int
    DEPRECATED_FIELD_NUMBER: _builtins.int
    SECURITY_FIELD_NUMBER: _builtins.int
    EXTENSIONS_FIELD_NUMBER: _builtins.int
    PARAMETERS_FIELD_NUMBER: _builtins.int
    summary: _builtins.str
    """A short summary of what the operation does. For maximum readability in the
    swagger-ui, this field SHOULD be less than 120 characters.
    """
    description: _builtins.str
    """A verbose explanation of the operation behavior. GFM syntax can be used for
    rich text representation.
    """
    operation_id: _builtins.str
    """Unique string used to identify the operation. The id MUST be unique among
    all operations described in the API. Tools and libraries MAY use the
    operationId to uniquely identify an operation, therefore, it is recommended
    to follow common programming naming conventions.
    """
    deprecated: _builtins.bool
    """Declares this operation to be deprecated. Usage of the declared operation
    should be refrained. Default value is false.
    """
    @_builtins.property
    def tags(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """A list of tags for API documentation control. Tags can be used for logical
        grouping of operations by resources or any other qualifier.
        """

    @_builtins.property
    def external_docs(self) -> Global___ExternalDocumentation:
        """Additional external documentation for this operation."""

    @_builtins.property
    def consumes(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """A list of MIME types the operation can consume. This overrides the consumes
        definition at the OpenAPI Object. An empty value MAY be used to clear the
        global definition. Value MUST be as described under Mime Types.
        """

    @_builtins.property
    def produces(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """A list of MIME types the operation can produce. This overrides the produces
        definition at the OpenAPI Object. An empty value MAY be used to clear the
        global definition. Value MUST be as described under Mime Types.
        """

    @_builtins.property
    def responses(self) -> _containers.MessageMap[_builtins.str, Global___Response]:
        """The list of possible responses as they are returned from executing this
        operation.
        """

    @_builtins.property
    def schemes(self) -> _containers.RepeatedScalarFieldContainer[Global___Scheme.ValueType]:
        """The transfer protocol for the operation. Values MUST be from the list:
        "http", "https", "ws", "wss". The value overrides the OpenAPI Object
        schemes definition.
        """

    @_builtins.property
    def security(self) -> _containers.RepeatedCompositeFieldContainer[Global___SecurityRequirement]:
        """A declaration of which security schemes are applied for this operation. The
        list of values describes alternative security schemes that can be used
        (that is, there is a logical OR between the security requirements). This
        definition overrides any declared top-level security. To remove a top-level
        security declaration, an empty array can be used.
        """

    @_builtins.property
    def extensions(self) -> _containers.MessageMap[_builtins.str, _struct_pb2.Value]:
        """Custom properties that start with "x-" such as "x-foo" used to describe
        extra functionality that is not covered by the standard OpenAPI Specification.
        See: https://swagger.io/docs/specification/2-0/swagger-extensions/
        """

    @_builtins.property
    def parameters(self) -> Global___Parameters:
        """Custom parameters such as HTTP request headers.
        See: https://swagger.io/docs/specification/2-0/describing-parameters/
        and https://swagger.io/specification/v2/#parameter-object.
        """

    def __init__(
        self,
        *,
        tags: _abc.Iterable[_builtins.str] | None = ...,
        summary: _builtins.str = ...,
        description: _builtins.str = ...,
        external_docs: Global___ExternalDocumentation | None = ...,
        operation_id: _builtins.str = ...,
        consumes: _abc.Iterable[_builtins.str] | None = ...,
        produces: _abc.Iterable[_builtins.str] | None = ...,
        responses: _abc.Mapping[_builtins.str, Global___Response] | None = ...,
        schemes: _abc.Iterable[Global___Scheme.ValueType] | None = ...,
        deprecated: _builtins.bool = ...,
        security: _abc.Iterable[Global___SecurityRequirement] | None = ...,
        extensions: _abc.Mapping[_builtins.str, _struct_pb2.Value] | None = ...,
        parameters: Global___Parameters | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["external_docs", b"external_docs", "parameters", b"parameters"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["consumes", b"consumes", "deprecated", b"deprecated", "description", b"description", "extensions", b"extensions", "external_docs", b"external_docs", "operation_id", b"operation_id", "parameters", b"parameters", "produces", b"produces", "responses", b"responses", "schemes", b"schemes", "security", b"security", "summary", b"summary", "tags", b"tags"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Operation: _TypeAlias = Operation  # noqa: Y015

@_typing.final
class Parameters(_message.Message):
    """`Parameters` is a representation of OpenAPI v2 specification's parameters object.
    Note: This technically breaks compatibility with the OpenAPI 2 definition structure as we only
    allow header parameters to be set here since we do not want users specifying custom non-header
    parameters beyond those inferred from the Protobuf schema.
    See: https://swagger.io/specification/v2/#parameter-object
    """

    DESCRIPTOR: _descriptor.Descriptor

    HEADERS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def headers(self) -> _containers.RepeatedCompositeFieldContainer[Global___HeaderParameter]:
        """`Headers` is one or more HTTP header parameter.
        See: https://swagger.io/docs/specification/2-0/describing-parameters/#header-parameters
        """

    def __init__(
        self,
        *,
        headers: _abc.Iterable[Global___HeaderParameter] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["headers", b"headers"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Parameters: _TypeAlias = Parameters  # noqa: Y015

@_typing.final
class HeaderParameter(_message.Message):
    """`HeaderParameter` a HTTP header parameter.
    See: https://swagger.io/specification/v2/#parameter-object
    """

    DESCRIPTOR: _descriptor.Descriptor

    class _Type:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _TypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[HeaderParameter._Type.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        UNKNOWN: HeaderParameter._Type.ValueType  # 0
        STRING: HeaderParameter._Type.ValueType  # 1
        NUMBER: HeaderParameter._Type.ValueType  # 2
        INTEGER: HeaderParameter._Type.ValueType  # 3
        BOOLEAN: HeaderParameter._Type.ValueType  # 4

    class Type(_Type, metaclass=_TypeEnumTypeWrapper):
        """`Type` is a supported HTTP header type.
        See https://swagger.io/specification/v2/#parameterType.
        """

    UNKNOWN: HeaderParameter.Type.ValueType  # 0
    STRING: HeaderParameter.Type.ValueType  # 1
    NUMBER: HeaderParameter.Type.ValueType  # 2
    INTEGER: HeaderParameter.Type.ValueType  # 3
    BOOLEAN: HeaderParameter.Type.ValueType  # 4

    NAME_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    FORMAT_FIELD_NUMBER: _builtins.int
    REQUIRED_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """`Name` is the header name."""
    description: _builtins.str
    """`Description` is a short description of the header."""
    type: Global___HeaderParameter.Type.ValueType
    """`Type` is the type of the object. The value MUST be one of "string", "number", "integer", or "boolean". The "array" type is not supported.
    See: https://swagger.io/specification/v2/#parameterType.
    """
    format: _builtins.str
    """`Format` The extending format for the previously mentioned type."""
    required: _builtins.bool
    """`Required` indicates if the header is optional"""
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        description: _builtins.str = ...,
        type: Global___HeaderParameter.Type.ValueType = ...,
        format: _builtins.str = ...,
        required: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["description", b"description", "format", b"format", "name", b"name", "required", b"required", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___HeaderParameter: _TypeAlias = HeaderParameter  # noqa: Y015

@_typing.final
class Header(_message.Message):
    """`Header` is a representation of OpenAPI v2 specification's Header object.

    See: https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#headerObject
    """

    DESCRIPTOR: _descriptor.Descriptor

    DESCRIPTION_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    FORMAT_FIELD_NUMBER: _builtins.int
    DEFAULT_FIELD_NUMBER: _builtins.int
    PATTERN_FIELD_NUMBER: _builtins.int
    description: _builtins.str
    """`Description` is a short description of the header."""
    type: _builtins.str
    """The type of the object. The value MUST be one of "string", "number", "integer", or "boolean". The "array" type is not supported."""
    format: _builtins.str
    """`Format` The extending format for the previously mentioned type."""
    default: _builtins.str
    """`Default` Declares the value of the header that the server will use if none is provided.
    See: https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-6.2.
    Unlike JSON Schema this value MUST conform to the defined type for the header.
    """
    pattern: _builtins.str
    """'Pattern' See https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-5.2.3."""
    def __init__(
        self,
        *,
        description: _builtins.str = ...,
        type: _builtins.str = ...,
        format: _builtins.str = ...,
        default: _builtins.str = ...,
        pattern: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["default", b"default", "description", b"description", "format", b"format", "pattern", b"pattern", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Header: _TypeAlias = Header  # noqa: Y015

@_typing.final
class Response(_message.Message):
    """`Response` is a representation of OpenAPI v2 specification's Response object.

    See: https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#responseObject
    """

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class HeadersEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> Global___Header: ...
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: Global___Header | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class ExamplesEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class ExtensionsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> _struct_pb2.Value: ...
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _struct_pb2.Value | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    DESCRIPTION_FIELD_NUMBER: _builtins.int
    SCHEMA_FIELD_NUMBER: _builtins.int
    HEADERS_FIELD_NUMBER: _builtins.int
    EXAMPLES_FIELD_NUMBER: _builtins.int
    EXTENSIONS_FIELD_NUMBER: _builtins.int
    description: _builtins.str
    """`Description` is a short description of the response.
    GFM syntax can be used for rich text representation.
    """
    @_builtins.property
    def schema(self) -> Global___Schema:
        """`Schema` optionally defines the structure of the response.
        If `Schema` is not provided, it means there is no content to the response.
        """

    @_builtins.property
    def headers(self) -> _containers.MessageMap[_builtins.str, Global___Header]:
        """`Headers` A list of headers that are sent with the response.
        `Header` name is expected to be a string in the canonical format of the MIME header key
        See: https://golang.org/pkg/net/textproto/#CanonicalMIMEHeaderKey
        """

    @_builtins.property
    def examples(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]:
        """`Examples` gives per-mimetype response examples.
        See: https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#example-object
        """

    @_builtins.property
    def extensions(self) -> _containers.MessageMap[_builtins.str, _struct_pb2.Value]:
        """Custom properties that start with "x-" such as "x-foo" used to describe
        extra functionality that is not covered by the standard OpenAPI Specification.
        See: https://swagger.io/docs/specification/2-0/swagger-extensions/
        """

    def __init__(
        self,
        *,
        description: _builtins.str = ...,
        schema: Global___Schema | None = ...,
        headers: _abc.Mapping[_builtins.str, Global___Header] | None = ...,
        examples: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        extensions: _abc.Mapping[_builtins.str, _struct_pb2.Value] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["schema", b"schema"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["description", b"description", "examples", b"examples", "extensions", b"extensions", "headers", b"headers", "schema", b"schema"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Response: _TypeAlias = Response  # noqa: Y015

@_typing.final
class Info(_message.Message):
    """`Info` is a representation of OpenAPI v2 specification's Info object.

    See: https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#infoObject

    Example:

     option (protoc_gen_openapiv2.options.openapiv2_swagger) = {
       info: {
         title: "Echo API";
         version: "1.0";
         description: "";
         contact: {
           name: "gRPC-Gateway project";
           url: "https://github.com/grpc-ecosystem/grpc-gateway";
           email: "none@example.com";
         };
         license: {
           name: "BSD 3-Clause License";
           url: "https://github.com/grpc-ecosystem/grpc-gateway/blob/main/LICENSE";
         };
       };
       ...
     };
    """

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class ExtensionsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> _struct_pb2.Value: ...
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _struct_pb2.Value | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    TITLE_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    TERMS_OF_SERVICE_FIELD_NUMBER: _builtins.int
    CONTACT_FIELD_NUMBER: _builtins.int
    LICENSE_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    EXTENSIONS_FIELD_NUMBER: _builtins.int
    title: _builtins.str
    """The title of the application."""
    description: _builtins.str
    """A short description of the application. GFM syntax can be used for rich
    text representation.
    """
    terms_of_service: _builtins.str
    """The Terms of Service for the API."""
    version: _builtins.str
    """Provides the version of the application API (not to be confused
    with the specification version).
    """
    @_builtins.property
    def contact(self) -> Global___Contact:
        """The contact information for the exposed API."""

    @_builtins.property
    def license(self) -> Global___License:
        """The license information for the exposed API."""

    @_builtins.property
    def extensions(self) -> _containers.MessageMap[_builtins.str, _struct_pb2.Value]:
        """Custom properties that start with "x-" such as "x-foo" used to describe
        extra functionality that is not covered by the standard OpenAPI Specification.
        See: https://swagger.io/docs/specification/2-0/swagger-extensions/
        """

    def __init__(
        self,
        *,
        title: _builtins.str = ...,
        description: _builtins.str = ...,
        terms_of_service: _builtins.str = ...,
        contact: Global___Contact | None = ...,
        license: Global___License | None = ...,
        version: _builtins.str = ...,
        extensions: _abc.Mapping[_builtins.str, _struct_pb2.Value] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["contact", b"contact", "license", b"license"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["contact", b"contact", "description", b"description", "extensions", b"extensions", "license", b"license", "terms_of_service", b"terms_of_service", "title", b"title", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Info: _TypeAlias = Info  # noqa: Y015

@_typing.final
class Contact(_message.Message):
    """`Contact` is a representation of OpenAPI v2 specification's Contact object.

    See: https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#contactObject

    Example:

     option (protoc_gen_openapiv2.options.openapiv2_swagger) = {
       info: {
         ...
         contact: {
           name: "gRPC-Gateway project";
           url: "https://github.com/grpc-ecosystem/grpc-gateway";
           email: "none@example.com";
         };
         ...
       };
       ...
     };
    """

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    URL_FIELD_NUMBER: _builtins.int
    EMAIL_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """The identifying name of the contact person/organization."""
    url: _builtins.str
    """The URL pointing to the contact information. MUST be in the format of a
    URL.
    """
    email: _builtins.str
    """The email address of the contact person/organization. MUST be in the format
    of an email address.
    """
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        url: _builtins.str = ...,
        email: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["email", b"email", "name", b"name", "url", b"url"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Contact: _TypeAlias = Contact  # noqa: Y015

@_typing.final
class License(_message.Message):
    """`License` is a representation of OpenAPI v2 specification's License object.

    See: https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#licenseObject

    Example:

     option (protoc_gen_openapiv2.options.openapiv2_swagger) = {
       info: {
         ...
         license: {
           name: "BSD 3-Clause License";
           url: "https://github.com/grpc-ecosystem/grpc-gateway/blob/main/LICENSE";
         };
         ...
       };
       ...
     };
    """

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    URL_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """The license name used for the API."""
    url: _builtins.str
    """A URL to the license used for the API. MUST be in the format of a URL."""
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        url: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["name", b"name", "url", b"url"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___License: _TypeAlias = License  # noqa: Y015

@_typing.final
class ExternalDocumentation(_message.Message):
    """`ExternalDocumentation` is a representation of OpenAPI v2 specification's
    ExternalDocumentation object.

    See: https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#externalDocumentationObject

    Example:

     option (protoc_gen_openapiv2.options.openapiv2_swagger) = {
       ...
       external_docs: {
         description: "More about gRPC-Gateway";
         url: "https://github.com/grpc-ecosystem/grpc-gateway";
       }
       ...
     };
    """

    DESCRIPTOR: _descriptor.Descriptor

    DESCRIPTION_FIELD_NUMBER: _builtins.int
    URL_FIELD_NUMBER: _builtins.int
    description: _builtins.str
    """A short description of the target documentation. GFM syntax can be used for
    rich text representation.
    """
    url: _builtins.str
    """The URL for the target documentation. Value MUST be in the format
    of a URL.
    """
    def __init__(
        self,
        *,
        description: _builtins.str = ...,
        url: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["description", b"description", "url", b"url"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ExternalDocumentation: _TypeAlias = ExternalDocumentation  # noqa: Y015

@_typing.final
class Schema(_message.Message):
    """`Schema` is a representation of OpenAPI v2 specification's Schema object.

    See: https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#schemaObject
    """

    DESCRIPTOR: _descriptor.Descriptor

    JSON_SCHEMA_FIELD_NUMBER: _builtins.int
    DISCRIMINATOR_FIELD_NUMBER: _builtins.int
    READ_ONLY_FIELD_NUMBER: _builtins.int
    EXTERNAL_DOCS_FIELD_NUMBER: _builtins.int
    EXAMPLE_FIELD_NUMBER: _builtins.int
    discriminator: _builtins.str
    """Adds support for polymorphism. The discriminator is the schema property
    name that is used to differentiate between other schema that inherit this
    schema. The property name used MUST be defined at this schema and it MUST
    be in the required property list. When used, the value MUST be the name of
    this schema or any schema that inherits it.
    """
    read_only: _builtins.bool
    """Relevant only for Schema "properties" definitions. Declares the property as
    "read only". This means that it MAY be sent as part of a response but MUST
    NOT be sent as part of the request. Properties marked as readOnly being
    true SHOULD NOT be in the required list of the defined schema. Default
    value is false.
    """
    example: _builtins.str
    """A free-form property to include an example of an instance for this schema in JSON.
    This is copied verbatim to the output.
    """
    @_builtins.property
    def json_schema(self) -> Global___JSONSchema: ...
    @_builtins.property
    def external_docs(self) -> Global___ExternalDocumentation:
        """Additional external documentation for this schema."""

    def __init__(
        self,
        *,
        json_schema: Global___JSONSchema | None = ...,
        discriminator: _builtins.str = ...,
        read_only: _builtins.bool = ...,
        external_docs: Global___ExternalDocumentation | None = ...,
        example: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["external_docs", b"external_docs", "json_schema", b"json_schema"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["discriminator", b"discriminator", "example", b"example", "external_docs", b"external_docs", "json_schema", b"json_schema", "read_only", b"read_only"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Schema: _TypeAlias = Schema  # noqa: Y015

@_typing.final
class EnumSchema(_message.Message):
    """`EnumSchema` is subset of fields from the OpenAPI v2 specification's Schema object.
    Only fields that are applicable to Enums are included
    See: https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#schemaObject

    Example:

     option (protoc_gen_openapiv2.options.openapiv2_enum) = {
       ...
       title: "MyEnum";
       description:"This is my nice enum";
       example: "ZERO";
       required: true;
       ...
     };
    """

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class ExtensionsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> _struct_pb2.Value: ...
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _struct_pb2.Value | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    DESCRIPTION_FIELD_NUMBER: _builtins.int
    DEFAULT_FIELD_NUMBER: _builtins.int
    TITLE_FIELD_NUMBER: _builtins.int
    REQUIRED_FIELD_NUMBER: _builtins.int
    READ_ONLY_FIELD_NUMBER: _builtins.int
    EXTERNAL_DOCS_FIELD_NUMBER: _builtins.int
    EXAMPLE_FIELD_NUMBER: _builtins.int
    REF_FIELD_NUMBER: _builtins.int
    EXTENSIONS_FIELD_NUMBER: _builtins.int
    description: _builtins.str
    """A short description of the schema."""
    default: _builtins.str
    title: _builtins.str
    """The title of the schema."""
    required: _builtins.bool
    read_only: _builtins.bool
    example: _builtins.str
    ref: _builtins.str
    """Ref is used to define an external reference to include in the message.
    This could be a fully qualified proto message reference, and that type must
    be imported into the protofile. If no message is identified, the Ref will
    be used verbatim in the output.
    For example:
     `ref: ".google.protobuf.Timestamp"`.
    """
    @_builtins.property
    def external_docs(self) -> Global___ExternalDocumentation:
        """Additional external documentation for this schema."""

    @_builtins.property
    def extensions(self) -> _containers.MessageMap[_builtins.str, _struct_pb2.Value]:
        """Custom properties that start with "x-" such as "x-foo" used to describe
        extra functionality that is not covered by the standard OpenAPI Specification.
        See: https://swagger.io/docs/specification/2-0/swagger-extensions/
        """

    def __init__(
        self,
        *,
        description: _builtins.str = ...,
        default: _builtins.str = ...,
        title: _builtins.str = ...,
        required: _builtins.bool = ...,
        read_only: _builtins.bool = ...,
        external_docs: Global___ExternalDocumentation | None = ...,
        example: _builtins.str = ...,
        ref: _builtins.str = ...,
        extensions: _abc.Mapping[_builtins.str, _struct_pb2.Value] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["external_docs", b"external_docs"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["default", b"default", "description", b"description", "example", b"example", "extensions", b"extensions", "external_docs", b"external_docs", "read_only", b"read_only", "ref", b"ref", "required", b"required", "title", b"title"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EnumSchema: _TypeAlias = EnumSchema  # noqa: Y015

@_typing.final
class JSONSchema(_message.Message):
    """`JSONSchema` represents properties from JSON Schema taken, and as used, in
    the OpenAPI v2 spec.

    This includes changes made by OpenAPI v2.

    See: https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#schemaObject

    See also: https://cswr.github.io/JsonSchema/spec/basic_types/,
    https://github.com/json-schema-org/json-schema-spec/blob/master/schema.json

    Example:

     message SimpleMessage {
       option (protoc_gen_openapiv2.options.openapiv2_schema) = {
         json_schema: {
           title: "SimpleMessage"
           description: "A simple message."
           required: ["id"]
         }
       };

       // Id represents the message identifier.
       string id = 1; [
           (protoc_gen_openapiv2.options.openapiv2_field) = {
             description: "The unique identifier of the simple message."
           }];
     }
    """

    DESCRIPTOR: _descriptor.Descriptor

    class _JSONSchemaSimpleTypes:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _JSONSchemaSimpleTypesEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[JSONSchema._JSONSchemaSimpleTypes.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        UNKNOWN: JSONSchema._JSONSchemaSimpleTypes.ValueType  # 0
        ARRAY: JSONSchema._JSONSchemaSimpleTypes.ValueType  # 1
        BOOLEAN: JSONSchema._JSONSchemaSimpleTypes.ValueType  # 2
        INTEGER: JSONSchema._JSONSchemaSimpleTypes.ValueType  # 3
        NULL: JSONSchema._JSONSchemaSimpleTypes.ValueType  # 4
        NUMBER: JSONSchema._JSONSchemaSimpleTypes.ValueType  # 5
        OBJECT: JSONSchema._JSONSchemaSimpleTypes.ValueType  # 6
        STRING: JSONSchema._JSONSchemaSimpleTypes.ValueType  # 7

    class JSONSchemaSimpleTypes(_JSONSchemaSimpleTypes, metaclass=_JSONSchemaSimpleTypesEnumTypeWrapper): ...
    UNKNOWN: JSONSchema.JSONSchemaSimpleTypes.ValueType  # 0
    ARRAY: JSONSchema.JSONSchemaSimpleTypes.ValueType  # 1
    BOOLEAN: JSONSchema.JSONSchemaSimpleTypes.ValueType  # 2
    INTEGER: JSONSchema.JSONSchemaSimpleTypes.ValueType  # 3
    NULL: JSONSchema.JSONSchemaSimpleTypes.ValueType  # 4
    NUMBER: JSONSchema.JSONSchemaSimpleTypes.ValueType  # 5
    OBJECT: JSONSchema.JSONSchemaSimpleTypes.ValueType  # 6
    STRING: JSONSchema.JSONSchemaSimpleTypes.ValueType  # 7

    @_typing.final
    class FieldConfiguration(_message.Message):
        """'FieldConfiguration' provides additional field level properties used when generating the OpenAPI v2 file.
        These properties are not defined by OpenAPIv2, but they are used to control the generation.
        """

        DESCRIPTOR: _descriptor.Descriptor

        PATH_PARAM_NAME_FIELD_NUMBER: _builtins.int
        path_param_name: _builtins.str
        """Alternative parameter name when used as path parameter. If set, this will
        be used as the complete parameter name when this field is used as a path
        parameter. Use this to avoid having auto generated path parameter names
        for overlapping paths.
        """
        def __init__(
            self,
            *,
            path_param_name: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["path_param_name", b"path_param_name"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class ExtensionsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> _struct_pb2.Value: ...
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _struct_pb2.Value | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    REF_FIELD_NUMBER: _builtins.int
    TITLE_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    DEFAULT_FIELD_NUMBER: _builtins.int
    READ_ONLY_FIELD_NUMBER: _builtins.int
    EXAMPLE_FIELD_NUMBER: _builtins.int
    MULTIPLE_OF_FIELD_NUMBER: _builtins.int
    MAXIMUM_FIELD_NUMBER: _builtins.int
    EXCLUSIVE_MAXIMUM_FIELD_NUMBER: _builtins.int
    MINIMUM_FIELD_NUMBER: _builtins.int
    EXCLUSIVE_MINIMUM_FIELD_NUMBER: _builtins.int
    MAX_LENGTH_FIELD_NUMBER: _builtins.int
    MIN_LENGTH_FIELD_NUMBER: _builtins.int
    PATTERN_FIELD_NUMBER: _builtins.int
    MAX_ITEMS_FIELD_NUMBER: _builtins.int
    MIN_ITEMS_FIELD_NUMBER: _builtins.int
    UNIQUE_ITEMS_FIELD_NUMBER: _builtins.int
    MAX_PROPERTIES_FIELD_NUMBER: _builtins.int
    MIN_PROPERTIES_FIELD_NUMBER: _builtins.int
    REQUIRED_FIELD_NUMBER: _builtins.int
    ARRAY_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    FORMAT_FIELD_NUMBER: _builtins.int
    ENUM_FIELD_NUMBER: _builtins.int
    FIELD_CONFIGURATION_FIELD_NUMBER: _builtins.int
    EXTENSIONS_FIELD_NUMBER: _builtins.int
    ref: _builtins.str
    """Ref is used to define an external reference to include in the message.
    This could be a fully qualified proto message reference, and that type must
    be imported into the protofile. If no message is identified, the Ref will
    be used verbatim in the output.
    For example:
     `ref: ".google.protobuf.Timestamp"`.
    """
    title: _builtins.str
    """The title of the schema."""
    description: _builtins.str
    """A short description of the schema."""
    default: _builtins.str
    read_only: _builtins.bool
    example: _builtins.str
    """A free-form property to include a JSON example of this field. This is copied
    verbatim to the output swagger.json. Quotes must be escaped.
    This property is the same for 2.0 and 3.0.0 https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/3.0.0.md#schemaObject  https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#schemaObject
    """
    multiple_of: _builtins.float
    maximum: _builtins.float
    """Maximum represents an inclusive upper limit for a numeric instance. The
    value of MUST be a number,
    """
    exclusive_maximum: _builtins.bool
    minimum: _builtins.float
    """minimum represents an inclusive lower limit for a numeric instance. The
    value of MUST be a number,
    """
    exclusive_minimum: _builtins.bool
    max_length: _builtins.int
    min_length: _builtins.int
    pattern: _builtins.str
    max_items: _builtins.int
    min_items: _builtins.int
    unique_items: _builtins.bool
    max_properties: _builtins.int
    min_properties: _builtins.int
    format: _builtins.str
    """`Format`"""
    @_builtins.property
    def required(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def array(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Items in 'array' must be unique."""

    @_builtins.property
    def type(self) -> _containers.RepeatedScalarFieldContainer[Global___JSONSchema.JSONSchemaSimpleTypes.ValueType]: ...
    @_builtins.property
    def enum(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Items in `enum` must be unique https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-5.5.1"""

    @_builtins.property
    def field_configuration(self) -> Global___JSONSchema.FieldConfiguration:
        """Additional field level properties used when generating the OpenAPI v2 file."""

    @_builtins.property
    def extensions(self) -> _containers.MessageMap[_builtins.str, _struct_pb2.Value]:
        """Custom properties that start with "x-" such as "x-foo" used to describe
        extra functionality that is not covered by the standard OpenAPI Specification.
        See: https://swagger.io/docs/specification/2-0/swagger-extensions/
        """

    def __init__(
        self,
        *,
        ref: _builtins.str = ...,
        title: _builtins.str = ...,
        description: _builtins.str = ...,
        default: _builtins.str = ...,
        read_only: _builtins.bool = ...,
        example: _builtins.str = ...,
        multiple_of: _builtins.float = ...,
        maximum: _builtins.float = ...,
        exclusive_maximum: _builtins.bool = ...,
        minimum: _builtins.float = ...,
        exclusive_minimum: _builtins.bool = ...,
        max_length: _builtins.int = ...,
        min_length: _builtins.int = ...,
        pattern: _builtins.str = ...,
        max_items: _builtins.int = ...,
        min_items: _builtins.int = ...,
        unique_items: _builtins.bool = ...,
        max_properties: _builtins.int = ...,
        min_properties: _builtins.int = ...,
        required: _abc.Iterable[_builtins.str] | None = ...,
        array: _abc.Iterable[_builtins.str] | None = ...,
        type: _abc.Iterable[Global___JSONSchema.JSONSchemaSimpleTypes.ValueType] | None = ...,
        format: _builtins.str = ...,
        enum: _abc.Iterable[_builtins.str] | None = ...,
        field_configuration: Global___JSONSchema.FieldConfiguration | None = ...,
        extensions: _abc.Mapping[_builtins.str, _struct_pb2.Value] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["field_configuration", b"field_configuration"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["array", b"array", "default", b"default", "description", b"description", "enum", b"enum", "example", b"example", "exclusive_maximum", b"exclusive_maximum", "exclusive_minimum", b"exclusive_minimum", "extensions", b"extensions", "field_configuration", b"field_configuration", "format", b"format", "max_items", b"max_items", "max_length", b"max_length", "max_properties", b"max_properties", "maximum", b"maximum", "min_items", b"min_items", "min_length", b"min_length", "min_properties", b"min_properties", "minimum", b"minimum", "multiple_of", b"multiple_of", "pattern", b"pattern", "read_only", b"read_only", "ref", b"ref", "required", b"required", "title", b"title", "type", b"type", "unique_items", b"unique_items"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___JSONSchema: _TypeAlias = JSONSchema  # noqa: Y015

@_typing.final
class Tag(_message.Message):
    """`Tag` is a representation of OpenAPI v2 specification's Tag object.

    See: https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#tagObject
    """

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class ExtensionsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> _struct_pb2.Value: ...
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _struct_pb2.Value | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    NAME_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    EXTERNAL_DOCS_FIELD_NUMBER: _builtins.int
    EXTENSIONS_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """The name of the tag. Use it to allow override of the name of a
    global Tag object, then use that name to reference the tag throughout the
    OpenAPI file.
    """
    description: _builtins.str
    """A short description for the tag. GFM syntax can be used for rich text
    representation.
    """
    @_builtins.property
    def external_docs(self) -> Global___ExternalDocumentation:
        """Additional external documentation for this tag."""

    @_builtins.property
    def extensions(self) -> _containers.MessageMap[_builtins.str, _struct_pb2.Value]:
        """Custom properties that start with "x-" such as "x-foo" used to describe
        extra functionality that is not covered by the standard OpenAPI Specification.
        See: https://swagger.io/docs/specification/2-0/swagger-extensions/
        """

    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        description: _builtins.str = ...,
        external_docs: Global___ExternalDocumentation | None = ...,
        extensions: _abc.Mapping[_builtins.str, _struct_pb2.Value] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["external_docs", b"external_docs"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["description", b"description", "extensions", b"extensions", "external_docs", b"external_docs", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Tag: _TypeAlias = Tag  # noqa: Y015

@_typing.final
class SecurityDefinitions(_message.Message):
    """`SecurityDefinitions` is a representation of OpenAPI v2 specification's
    Security Definitions object.

    See: https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#securityDefinitionsObject

    A declaration of the security schemes available to be used in the
    specification. This does not enforce the security schemes on the operations
    and only serves to provide the relevant details for each scheme.
    """

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class SecurityEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> Global___SecurityScheme: ...
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: Global___SecurityScheme | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    SECURITY_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def security(self) -> _containers.MessageMap[_builtins.str, Global___SecurityScheme]:
        """A single security scheme definition, mapping a "name" to the scheme it
        defines.
        """

    def __init__(
        self,
        *,
        security: _abc.Mapping[_builtins.str, Global___SecurityScheme] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["security", b"security"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SecurityDefinitions: _TypeAlias = SecurityDefinitions  # noqa: Y015

@_typing.final
class SecurityScheme(_message.Message):
    """`SecurityScheme` is a representation of OpenAPI v2 specification's
    Security Scheme object.

    See: https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#securitySchemeObject

    Allows the definition of a security scheme that can be used by the
    operations. Supported schemes are basic authentication, an API key (either as
    a header or as a query parameter) and OAuth2's common flows (implicit,
    password, application and access code).
    """

    DESCRIPTOR: _descriptor.Descriptor

    class _Type:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _TypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[SecurityScheme._Type.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        TYPE_INVALID: SecurityScheme._Type.ValueType  # 0
        TYPE_BASIC: SecurityScheme._Type.ValueType  # 1
        TYPE_API_KEY: SecurityScheme._Type.ValueType  # 2
        TYPE_OAUTH2: SecurityScheme._Type.ValueType  # 3

    class Type(_Type, metaclass=_TypeEnumTypeWrapper):
        """The type of the security scheme. Valid values are "basic",
        "apiKey" or "oauth2".
        """

    TYPE_INVALID: SecurityScheme.Type.ValueType  # 0
    TYPE_BASIC: SecurityScheme.Type.ValueType  # 1
    TYPE_API_KEY: SecurityScheme.Type.ValueType  # 2
    TYPE_OAUTH2: SecurityScheme.Type.ValueType  # 3

    class _In:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _InEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[SecurityScheme._In.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        IN_INVALID: SecurityScheme._In.ValueType  # 0
        IN_QUERY: SecurityScheme._In.ValueType  # 1
        IN_HEADER: SecurityScheme._In.ValueType  # 2

    class In(_In, metaclass=_InEnumTypeWrapper):
        """The location of the API key. Valid values are "query" or "header"."""

    IN_INVALID: SecurityScheme.In.ValueType  # 0
    IN_QUERY: SecurityScheme.In.ValueType  # 1
    IN_HEADER: SecurityScheme.In.ValueType  # 2

    class _Flow:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _FlowEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[SecurityScheme._Flow.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        FLOW_INVALID: SecurityScheme._Flow.ValueType  # 0
        FLOW_IMPLICIT: SecurityScheme._Flow.ValueType  # 1
        FLOW_PASSWORD: SecurityScheme._Flow.ValueType  # 2
        FLOW_APPLICATION: SecurityScheme._Flow.ValueType  # 3
        FLOW_ACCESS_CODE: SecurityScheme._Flow.ValueType  # 4

    class Flow(_Flow, metaclass=_FlowEnumTypeWrapper):
        """The flow used by the OAuth2 security scheme. Valid values are
        "implicit", "password", "application" or "accessCode".
        """

    FLOW_INVALID: SecurityScheme.Flow.ValueType  # 0
    FLOW_IMPLICIT: SecurityScheme.Flow.ValueType  # 1
    FLOW_PASSWORD: SecurityScheme.Flow.ValueType  # 2
    FLOW_APPLICATION: SecurityScheme.Flow.ValueType  # 3
    FLOW_ACCESS_CODE: SecurityScheme.Flow.ValueType  # 4

    @_typing.final
    class ExtensionsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> _struct_pb2.Value: ...
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _struct_pb2.Value | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    TYPE_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    IN_FIELD_NUMBER: _builtins.int
    FLOW_FIELD_NUMBER: _builtins.int
    AUTHORIZATION_URL_FIELD_NUMBER: _builtins.int
    TOKEN_URL_FIELD_NUMBER: _builtins.int
    SCOPES_FIELD_NUMBER: _builtins.int
    EXTENSIONS_FIELD_NUMBER: _builtins.int
    type: Global___SecurityScheme.Type.ValueType
    """The type of the security scheme. Valid values are "basic",
    "apiKey" or "oauth2".
    """
    description: _builtins.str
    """A short description for security scheme."""
    name: _builtins.str
    """The name of the header or query parameter to be used.
    Valid for apiKey.
    """
    flow: Global___SecurityScheme.Flow.ValueType
    """The flow used by the OAuth2 security scheme. Valid values are
    "implicit", "password", "application" or "accessCode".
    Valid for oauth2.
    """
    authorization_url: _builtins.str
    """The authorization URL to be used for this flow. This SHOULD be in
    the form of a URL.
    Valid for oauth2/implicit and oauth2/accessCode.
    """
    token_url: _builtins.str
    """The token URL to be used for this flow. This SHOULD be in the
    form of a URL.
    Valid for oauth2/password, oauth2/application and oauth2/accessCode.
    """
    @_builtins.property
    def scopes(self) -> Global___Scopes:
        """The available scopes for the OAuth2 security scheme.
        Valid for oauth2.
        """

    @_builtins.property
    def extensions(self) -> _containers.MessageMap[_builtins.str, _struct_pb2.Value]:
        """Custom properties that start with "x-" such as "x-foo" used to describe
        extra functionality that is not covered by the standard OpenAPI Specification.
        See: https://swagger.io/docs/specification/2-0/swagger-extensions/
        """

    def __init__(
        self,
        *,
        type: Global___SecurityScheme.Type.ValueType = ...,
        description: _builtins.str = ...,
        name: _builtins.str = ...,
        flow: Global___SecurityScheme.Flow.ValueType = ...,
        authorization_url: _builtins.str = ...,
        token_url: _builtins.str = ...,
        scopes: Global___Scopes | None = ...,
        extensions: _abc.Mapping[_builtins.str, _struct_pb2.Value] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["scopes", b"scopes"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["authorization_url", b"authorization_url", "description", b"description", "extensions", b"extensions", "flow", b"flow", "in", b"in", "name", b"name", "scopes", b"scopes", "token_url", b"token_url", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SecurityScheme: _TypeAlias = SecurityScheme  # noqa: Y015

@_typing.final
class SecurityRequirement(_message.Message):
    """`SecurityRequirement` is a representation of OpenAPI v2 specification's
    Security Requirement object.

    See: https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#securityRequirementObject

    Lists the required security schemes to execute this operation. The object can
    have multiple security schemes declared in it which are all required (that
    is, there is a logical AND between the schemes).

    The name used for each property MUST correspond to a security scheme
    declared in the Security Definitions.
    """

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class SecurityRequirementValue(_message.Message):
        """If the security scheme is of type "oauth2", then the value is a list of
        scope names required for the execution. For other security scheme types,
        the array MUST be empty.
        """

        DESCRIPTOR: _descriptor.Descriptor

        SCOPE_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def scope(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
        def __init__(
            self,
            *,
            scope: _abc.Iterable[_builtins.str] | None = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["scope", b"scope"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class SecurityRequirementEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> Global___SecurityRequirement.SecurityRequirementValue: ...
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: Global___SecurityRequirement.SecurityRequirementValue | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    SECURITY_REQUIREMENT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def security_requirement(self) -> _containers.MessageMap[_builtins.str, Global___SecurityRequirement.SecurityRequirementValue]:
        """Each name must correspond to a security scheme which is declared in
        the Security Definitions. If the security scheme is of type "oauth2",
        then the value is a list of scope names required for the execution.
        For other security scheme types, the array MUST be empty.
        """

    def __init__(
        self,
        *,
        security_requirement: _abc.Mapping[_builtins.str, Global___SecurityRequirement.SecurityRequirementValue] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["security_requirement", b"security_requirement"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SecurityRequirement: _TypeAlias = SecurityRequirement  # noqa: Y015

@_typing.final
class Scopes(_message.Message):
    """`Scopes` is a representation of OpenAPI v2 specification's Scopes object.

    See: https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#scopesObject

    Lists the available scopes for an OAuth2 security scheme.
    """

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class ScopeEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    SCOPE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def scope(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]:
        """Maps between a name of a scope to a short description of it (as the value
        of the property).
        """

    def __init__(
        self,
        *,
        scope: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["scope", b"scope"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Scopes: _TypeAlias = Scopes  # noqa: Y015
