"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf import wrappers_pb2 as _wrappers_pb2
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _ReportForm:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ReportFormEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ReportForm.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    REPORT_FORM_UNKNOWN: _ReportForm.ValueType  # 0
    """Не указана"""
    REPORT_FORM_SHORT: _ReportForm.ValueType  # 1
    """Краткая"""
    REPORT_FORM_LONG: _ReportForm.ValueType  # 2
    """Полная"""

class ReportForm(_ReportForm, metaclass=_ReportFormEnumTypeWrapper):
    """Форма отчета"""

REPORT_FORM_UNKNOWN: ReportForm.ValueType  # 0
"""Не указана"""
REPORT_FORM_SHORT: ReportForm.ValueType  # 1
"""Краткая"""
REPORT_FORM_LONG: ReportForm.ValueType  # 2
"""Полная"""
Global___ReportForm: _TypeAlias = ReportForm  # noqa: Y015

class _ReportCreationStatus:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ReportCreationStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ReportCreationStatus.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    NOT_FOUND: _ReportCreationStatus.ValueType  # 0
    """Не найден"""
    PENDING: _ReportCreationStatus.ValueType  # 1
    """Ожидает генерации"""
    IN_PROGRESS: _ReportCreationStatus.ValueType  # 2
    """Генерация запущена"""
    SUCCESS: _ReportCreationStatus.ValueType  # 3
    """Генерация завершена успешно"""
    ERROR: _ReportCreationStatus.ValueType  # 4
    """Генерация завершена с ошибкой"""

class ReportCreationStatus(_ReportCreationStatus, metaclass=_ReportCreationStatusEnumTypeWrapper):
    """Статус генерации отчёта"""

NOT_FOUND: ReportCreationStatus.ValueType  # 0
"""Не найден"""
PENDING: ReportCreationStatus.ValueType  # 1
"""Ожидает генерации"""
IN_PROGRESS: ReportCreationStatus.ValueType  # 2
"""Генерация запущена"""
SUCCESS: ReportCreationStatus.ValueType  # 3
"""Генерация завершена успешно"""
ERROR: ReportCreationStatus.ValueType  # 4
"""Генерация завершена с ошибкой"""
Global___ReportCreationStatus: _TypeAlias = ReportCreationStatus  # noqa: Y015

@_typing.final
class CreateAccountReportRequest(_message.Message):
    """Запрос на генерацию отчёта по счёту за период"""

    DESCRIPTOR: _descriptor.Descriptor

    DATE_RANGE_FIELD_NUMBER: _builtins.int
    REPORT_FORM_FIELD_NUMBER: _builtins.int
    ACCOUNT_ID_FIELD_NUMBER: _builtins.int
    report_form: Global___ReportForm.ValueType
    """Форма отчета"""
    account_id: _builtins.int
    """Идентификатор счета"""
    @_builtins.property
    def date_range(self) -> Global___DateRange:
        """Временной интервал. Максимальный интервал дат - 92 дня"""

    def __init__(
        self,
        *,
        date_range: Global___DateRange | None = ...,
        report_form: Global___ReportForm.ValueType = ...,
        account_id: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["date_range", b"date_range"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["account_id", b"account_id", "date_range", b"date_range", "report_form", b"report_form"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CreateAccountReportRequest: _TypeAlias = CreateAccountReportRequest  # noqa: Y015

@_typing.final
class CreateAccountReportResponse(_message.Message):
    """Информация о генерируемом отчёте"""

    DESCRIPTOR: _descriptor.Descriptor

    REPORT_ID_FIELD_NUMBER: _builtins.int
    report_id: _builtins.str
    """Идентификатор отчёта"""
    def __init__(
        self,
        *,
        report_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["report_id", b"report_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CreateAccountReportResponse: _TypeAlias = CreateAccountReportResponse  # noqa: Y015

@_typing.final
class GetAccountReportInfoRequest(_message.Message):
    """Запрос на получение статуса генерации отчёта"""

    DESCRIPTOR: _descriptor.Descriptor

    REPORT_ID_FIELD_NUMBER: _builtins.int
    report_id: _builtins.str
    """Идентификатор отчёта"""
    def __init__(
        self,
        *,
        report_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["report_id", b"report_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetAccountReportInfoRequest: _TypeAlias = GetAccountReportInfoRequest  # noqa: Y015

@_typing.final
class GetAccountReportInfoResponse(_message.Message):
    """Информация о статусе генерации отчёта"""

    DESCRIPTOR: _descriptor.Descriptor

    INFO_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def info(self) -> Global___AccountReportInfo:
        """Информация о статусе генерации отчёта"""

    def __init__(
        self,
        *,
        info: Global___AccountReportInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["info", b"info"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["info", b"info"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetAccountReportInfoResponse: _TypeAlias = GetAccountReportInfoResponse  # noqa: Y015

@_typing.final
class SubscribeAccountReportInfoRequest(_message.Message):
    """Запрос подписки на получение статуса генерации отчёта"""

    DESCRIPTOR: _descriptor.Descriptor

    REPORT_ID_FIELD_NUMBER: _builtins.int
    report_id: _builtins.str
    """Идентификатор отчёта"""
    def __init__(
        self,
        *,
        report_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["report_id", b"report_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SubscribeAccountReportInfoRequest: _TypeAlias = SubscribeAccountReportInfoRequest  # noqa: Y015

@_typing.final
class SubscribeAccountReportInfoResponse(_message.Message):
    """Информация о статусе генерации отчёта. Стрим"""

    DESCRIPTOR: _descriptor.Descriptor

    INFO_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def info(self) -> Global___AccountReportInfo:
        """Информация о статусе генерации отчёта"""

    def __init__(
        self,
        *,
        info: Global___AccountReportInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["info", b"info"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["info", b"info"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SubscribeAccountReportInfoResponse: _TypeAlias = SubscribeAccountReportInfoResponse  # noqa: Y015

@_typing.final
class AccountReportInfo(_message.Message):
    """Информация о статусе генерации отчёта"""

    DESCRIPTOR: _descriptor.Descriptor

    REPORT_ID_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    DATE_RANGE_FIELD_NUMBER: _builtins.int
    REPORT_FORM_FIELD_NUMBER: _builtins.int
    ACCOUNT_ID_FIELD_NUMBER: _builtins.int
    URL_FIELD_NUMBER: _builtins.int
    report_id: _builtins.str
    """Идентификатор отчёта"""
    status: Global___ReportCreationStatus.ValueType
    """Статус генерации отчёта"""
    report_form: Global___ReportForm.ValueType
    """Форма отчета. Берётся из запроса на генерацию отчёта"""
    account_id: _builtins.int
    """Идентификатор счета. Берётся из запроса на генерацию отчёта"""
    @_builtins.property
    def date_range(self) -> Global___DateRange:
        """Временной интервал отчёта. Берётся из запроса на генерацию отчёта"""

    @_builtins.property
    def url(self) -> _wrappers_pb2.StringValue:
        """Ссылка на скачивание отчёта. Появляется только в случае успешной генерации отчёта (ReportCreationStatus = SUCCESS)"""

    def __init__(
        self,
        *,
        report_id: _builtins.str = ...,
        status: Global___ReportCreationStatus.ValueType = ...,
        date_range: Global___DateRange | None = ...,
        report_form: Global___ReportForm.ValueType = ...,
        account_id: _builtins.int = ...,
        url: _wrappers_pb2.StringValue | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["date_range", b"date_range", "url", b"url"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["account_id", b"account_id", "date_range", b"date_range", "report_form", b"report_form", "report_id", b"report_id", "status", b"status", "url", b"url"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AccountReportInfo: _TypeAlias = AccountReportInfo  # noqa: Y015

@_typing.final
class DateRange(_message.Message):
    """Временной интервал"""

    DESCRIPTOR: _descriptor.Descriptor

    DATE_BEGIN_FIELD_NUMBER: _builtins.int
    DATE_END_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def date_begin(self) -> _timestamp_pb2.Timestamp:
        """Дата начала временного интервала"""

    @_builtins.property
    def date_end(self) -> _timestamp_pb2.Timestamp:
        """Дата конца временного интервала"""

    def __init__(
        self,
        *,
        date_begin: _timestamp_pb2.Timestamp | None = ...,
        date_end: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["date_begin", b"date_begin", "date_end", b"date_end"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["date_begin", b"date_begin", "date_end", b"date_end"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DateRange: _TypeAlias = DateRange  # noqa: Y015
