"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from FinamPy.grpc import trade_pb2 as _trade_pb2
from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.type import decimal_pb2 as _decimal_pb2
from google.type import interval_pb2 as _interval_pb2
from google.type import money_pb2 as _money_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

if sys.version_info >= (3, 13):
    from warnings import deprecated as _deprecated
else:
    from typing_extensions import deprecated as _deprecated

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class GetAccountRequest(_message.Message):
    """Запрос получения информации по конкретному аккаунту"""

    DESCRIPTOR: _descriptor.Descriptor

    ACCOUNT_ID_FIELD_NUMBER: _builtins.int
    account_id: _builtins.str
    """Идентификатор аккаунта"""
    def __init__(
        self,
        *,
        account_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["account_id", b"account_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetAccountRequest: _TypeAlias = GetAccountRequest  # noqa: Y015

@_typing.final
class GetAccountResponse(_message.Message):
    """Информация о конкретном аккаунте"""

    DESCRIPTOR: _descriptor.Descriptor

    ACCOUNT_ID_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    EQUITY_FIELD_NUMBER: _builtins.int
    UNREALIZED_PROFIT_FIELD_NUMBER: _builtins.int
    POSITIONS_FIELD_NUMBER: _builtins.int
    CASH_FIELD_NUMBER: _builtins.int
    PORTFOLIO_MC_FIELD_NUMBER: _builtins.int
    PORTFOLIO_MCT_FIELD_NUMBER: _builtins.int
    PORTFOLIO_FORTS_FIELD_NUMBER: _builtins.int
    OPEN_ACCOUNT_DATE_FIELD_NUMBER: _builtins.int
    FIRST_TRADE_DATE_FIELD_NUMBER: _builtins.int
    FIRST_NON_TRADE_DATE_FIELD_NUMBER: _builtins.int
    account_id: _builtins.str
    """Идентификатор аккаунта"""
    type: _builtins.str
    """Тип аккаунта"""
    status: _builtins.str
    """Статус аккаунта"""
    @_builtins.property
    def equity(self) -> _decimal_pb2.Decimal:
        """Доступные средства плюс стоимость открытых позиций"""

    @_builtins.property
    def unrealized_profit(self) -> _decimal_pb2.Decimal:
        """Нереализованная прибыль"""

    @_builtins.property
    def positions(self) -> _containers.RepeatedCompositeFieldContainer[Global___Position]:
        """Позиции. Открытые, плюс теоретические (по неисполненным активным заявкам)"""

    @_builtins.property
    def cash(self) -> _containers.RepeatedCompositeFieldContainer[_money_pb2.Money]:
        """Сумма собственных денежных средств на счете, доступная для торговли. Не включает маржинальные средства."""

    @_builtins.property
    def portfolio_mc(self) -> Global___MC:
        """Общий тип для счетов Московской Биржи. Включает в себя как единые, так и моно счета."""

    @_builtins.property
    def portfolio_mct(self) -> Global___MCT:
        """Тип портфеля для счетов на американских рынках."""

    @_builtins.property
    def portfolio_forts(self) -> Global___FORTS:
        """Тип портфеля для торговли на срочном рынке Московской Биржи."""

    @_builtins.property
    def open_account_date(self) -> _timestamp_pb2.Timestamp:
        """Дата открытия счета"""

    @_builtins.property
    def first_trade_date(self) -> _timestamp_pb2.Timestamp:
        """Дата первой торговой транзакции"""

    @_builtins.property
    def first_non_trade_date(self) -> _timestamp_pb2.Timestamp:
        """Дата первой неторговой транзакции"""

    def __init__(
        self,
        *,
        account_id: _builtins.str = ...,
        type: _builtins.str = ...,
        status: _builtins.str = ...,
        equity: _decimal_pb2.Decimal | None = ...,
        unrealized_profit: _decimal_pb2.Decimal | None = ...,
        positions: _abc.Iterable[Global___Position] | None = ...,
        cash: _abc.Iterable[_money_pb2.Money] | None = ...,
        portfolio_mc: Global___MC | None = ...,
        portfolio_mct: Global___MCT | None = ...,
        portfolio_forts: Global___FORTS | None = ...,
        open_account_date: _timestamp_pb2.Timestamp | None = ...,
        first_trade_date: _timestamp_pb2.Timestamp | None = ...,
        first_non_trade_date: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["equity", b"equity", "first_non_trade_date", b"first_non_trade_date", "first_trade_date", b"first_trade_date", "open_account_date", b"open_account_date", "portfolio", b"portfolio", "portfolio_forts", b"portfolio_forts", "portfolio_mc", b"portfolio_mc", "portfolio_mct", b"portfolio_mct", "unrealized_profit", b"unrealized_profit"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["account_id", b"account_id", "cash", b"cash", "equity", b"equity", "first_non_trade_date", b"first_non_trade_date", "first_trade_date", b"first_trade_date", "open_account_date", b"open_account_date", "portfolio", b"portfolio", "portfolio_forts", b"portfolio_forts", "portfolio_mc", b"portfolio_mc", "portfolio_mct", b"portfolio_mct", "positions", b"positions", "status", b"status", "type", b"type", "unrealized_profit", b"unrealized_profit"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_portfolio: _TypeAlias = _typing.Literal["portfolio_mc", "portfolio_mct", "portfolio_forts"]  # noqa: Y015
    _WhichOneofArgType_portfolio: _TypeAlias = _typing.Literal["portfolio", b"portfolio"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_portfolio) -> _WhichOneofReturnType_portfolio | None: ...

Global___GetAccountResponse: _TypeAlias = GetAccountResponse  # noqa: Y015

@_typing.final
class MC(_message.Message):
    """Общий тип для счетов Московской Биржи. Включает в себя как единые, так и специализированные (моно) счета для разных секций биржи.
    Единый торговый счет (ЕТС): Позволяет торговать на нескольких рынках (фондовый, валютный. срочный, spb, иностранные бумаги, иностранные фьючерсы) с единой денежной позиции.
    Моно-счет фондового рынка MOEX: Изолированный счет для торговли акциями, облигациями и паями.
    Моно-счет валютного рынка MOEX: Изолированный счет для операций с валютными парами (например, CNYRUB_TOM).
    """

    DESCRIPTOR: _descriptor.Descriptor

    AVAILABLE_CASH_FIELD_NUMBER: _builtins.int
    INITIAL_MARGIN_FIELD_NUMBER: _builtins.int
    MAINTENANCE_MARGIN_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def available_cash(self) -> _decimal_pb2.Decimal:
        """Сумма собственных денежных средств на счете, доступная для торговли. Включает маржинальные средства."""

    @_builtins.property
    def initial_margin(self) -> _decimal_pb2.Decimal:
        """Начальная маржа"""

    @_builtins.property
    def maintenance_margin(self) -> _decimal_pb2.Decimal:
        """Минимальная маржа"""

    def __init__(
        self,
        *,
        available_cash: _decimal_pb2.Decimal | None = ...,
        initial_margin: _decimal_pb2.Decimal | None = ...,
        maintenance_margin: _decimal_pb2.Decimal | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["available_cash", b"available_cash", "initial_margin", b"initial_margin", "maintenance_margin", b"maintenance_margin"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["available_cash", b"available_cash", "initial_margin", b"initial_margin", "maintenance_margin", b"maintenance_margin"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MC: _TypeAlias = MC  # noqa: Y015

@_typing.final
class MCT(_message.Message):
    """Тип портфеля для счетов на американских рынках.
    Предоставляет доступ к биржам США: NYSE, NASDAQ, CBOE, CME, сделки с американскими акциями, фьючерсами и опционами.
    """

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___MCT: _TypeAlias = MCT  # noqa: Y015

@_typing.final
class FORTS(_message.Message):
    """Тип портфеля для торговли на срочном рынке Московской Биржи.
    Предназначен для работы с производными финансовыми инструментами: фьючерсами и опционами.
    """

    DESCRIPTOR: _descriptor.Descriptor

    AVAILABLE_CASH_FIELD_NUMBER: _builtins.int
    MONEY_RESERVED_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def available_cash(self) -> _decimal_pb2.Decimal:
        """Сумма собственных денежных средств на счете, доступная для торговли. Включает маржинальные средства."""

    @_builtins.property
    def money_reserved(self) -> _decimal_pb2.Decimal:
        """Минимальная маржа (необходимая сумма обеспечения под открытые позици)"""

    def __init__(
        self,
        *,
        available_cash: _decimal_pb2.Decimal | None = ...,
        money_reserved: _decimal_pb2.Decimal | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["available_cash", b"available_cash", "money_reserved", b"money_reserved"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["available_cash", b"available_cash", "money_reserved", b"money_reserved"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___FORTS: _TypeAlias = FORTS  # noqa: Y015

@_typing.final
class TradesRequest(_message.Message):
    """Запрос получения истории по сделкам"""

    DESCRIPTOR: _descriptor.Descriptor

    ACCOUNT_ID_FIELD_NUMBER: _builtins.int
    LIMIT_FIELD_NUMBER: _builtins.int
    INTERVAL_FIELD_NUMBER: _builtins.int
    account_id: _builtins.str
    """Идентификатор аккаунта"""
    limit: _builtins.int
    """Лимит количества сделок"""
    @_builtins.property
    def interval(self) -> _interval_pb2.Interval:
        """Начало и окончание запрашиваемого периода, Unix epoch time"""

    def __init__(
        self,
        *,
        account_id: _builtins.str = ...,
        limit: _builtins.int = ...,
        interval: _interval_pb2.Interval | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["interval", b"interval"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["account_id", b"account_id", "interval", b"interval", "limit", b"limit"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TradesRequest: _TypeAlias = TradesRequest  # noqa: Y015

@_typing.final
class TradesResponse(_message.Message):
    """История по сделкам"""

    DESCRIPTOR: _descriptor.Descriptor

    TRADES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def trades(self) -> _containers.RepeatedCompositeFieldContainer[_trade_pb2.AccountTrade]:
        """Сделки по аккаунту"""

    def __init__(
        self,
        *,
        trades: _abc.Iterable[_trade_pb2.AccountTrade] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["trades", b"trades"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TradesResponse: _TypeAlias = TradesResponse  # noqa: Y015

@_typing.final
class TransactionsRequest(_message.Message):
    """Запрос получения списка транзакций"""

    DESCRIPTOR: _descriptor.Descriptor

    ACCOUNT_ID_FIELD_NUMBER: _builtins.int
    LIMIT_FIELD_NUMBER: _builtins.int
    INTERVAL_FIELD_NUMBER: _builtins.int
    account_id: _builtins.str
    """Идентификатор аккаунта"""
    limit: _builtins.int
    """Лимит количества транзакций"""
    @_builtins.property
    def interval(self) -> _interval_pb2.Interval:
        """Начало и окончание запрашиваемого периода, Unix epoch time"""

    def __init__(
        self,
        *,
        account_id: _builtins.str = ...,
        limit: _builtins.int = ...,
        interval: _interval_pb2.Interval | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["interval", b"interval"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["account_id", b"account_id", "interval", b"interval", "limit", b"limit"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TransactionsRequest: _TypeAlias = TransactionsRequest  # noqa: Y015

@_typing.final
class TransactionsResponse(_message.Message):
    """Список транзакций"""

    DESCRIPTOR: _descriptor.Descriptor

    TRANSACTIONS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def transactions(self) -> _containers.RepeatedCompositeFieldContainer[Global___Transaction]:
        """Транзакции по аккаунту"""

    def __init__(
        self,
        *,
        transactions: _abc.Iterable[Global___Transaction] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["transactions", b"transactions"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TransactionsResponse: _TypeAlias = TransactionsResponse  # noqa: Y015

@_typing.final
class Position(_message.Message):
    """Информация о позиции"""

    DESCRIPTOR: _descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: _builtins.int
    QUANTITY_FIELD_NUMBER: _builtins.int
    AVERAGE_PRICE_FIELD_NUMBER: _builtins.int
    CURRENT_PRICE_FIELD_NUMBER: _builtins.int
    MAINTENANCE_MARGIN_FIELD_NUMBER: _builtins.int
    DAILY_PNL_FIELD_NUMBER: _builtins.int
    UNREALIZED_PNL_FIELD_NUMBER: _builtins.int
    symbol: _builtins.str
    """Символ инструмента"""
    @_builtins.property
    def quantity(self) -> _decimal_pb2.Decimal:
        """Количество в шт., значение со знаком определяющее (long-short)"""

    @_builtins.property
    def average_price(self) -> _decimal_pb2.Decimal:
        """Средняя цена. Не заполняется для FORTS позиций"""

    @_builtins.property
    def current_price(self) -> _decimal_pb2.Decimal:
        """Текущая цена"""

    @_builtins.property
    def maintenance_margin(self) -> _decimal_pb2.Decimal:
        """Поддерживающее гарантийное обеспечение. Заполняется только для FORTS позиций"""

    @_builtins.property
    def daily_pnl(self) -> _decimal_pb2.Decimal:
        """Прибыль или убыток за текущий день (PnL). Не заполняется для FORTS позиций"""

    @_builtins.property
    def unrealized_pnl(self) -> _decimal_pb2.Decimal:
        """Суммарная нереализованная прибыль или убыток (PnL) текущей позиции"""

    def __init__(
        self,
        *,
        symbol: _builtins.str = ...,
        quantity: _decimal_pb2.Decimal | None = ...,
        average_price: _decimal_pb2.Decimal | None = ...,
        current_price: _decimal_pb2.Decimal | None = ...,
        maintenance_margin: _decimal_pb2.Decimal | None = ...,
        daily_pnl: _decimal_pb2.Decimal | None = ...,
        unrealized_pnl: _decimal_pb2.Decimal | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["average_price", b"average_price", "current_price", b"current_price", "daily_pnl", b"daily_pnl", "maintenance_margin", b"maintenance_margin", "quantity", b"quantity", "unrealized_pnl", b"unrealized_pnl"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["average_price", b"average_price", "current_price", b"current_price", "daily_pnl", b"daily_pnl", "maintenance_margin", b"maintenance_margin", "quantity", b"quantity", "symbol", b"symbol", "unrealized_pnl", b"unrealized_pnl"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Position: _TypeAlias = Position  # noqa: Y015

@_typing.final
class Transaction(_message.Message):
    """Информация о транзакции"""

    DESCRIPTOR: _descriptor.Descriptor

    class _TransactionCategory:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _TransactionCategoryEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Transaction._TransactionCategory.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        OTHERS: Transaction._TransactionCategory.ValueType  # 0
        """Прочее"""
        DEPOSIT: Transaction._TransactionCategory.ValueType  # 1
        """Ввод ДС"""
        WITHDRAW: Transaction._TransactionCategory.ValueType  # 2
        """Вывод ДС"""
        INCOME: Transaction._TransactionCategory.ValueType  # 5
        """Доход"""
        COMMISSION: Transaction._TransactionCategory.ValueType  # 7
        """Комиссия"""
        TAX: Transaction._TransactionCategory.ValueType  # 8
        """Налог"""
        INHERITANCE: Transaction._TransactionCategory.ValueType  # 9
        """Наследство"""
        TRANSFER: Transaction._TransactionCategory.ValueType  # 11
        """Перевод ДС"""
        CONTRACT_TERMINATION: Transaction._TransactionCategory.ValueType  # 12
        """Расторжение договора"""
        OUTCOMES: Transaction._TransactionCategory.ValueType  # 13
        """Расходы"""
        FINE: Transaction._TransactionCategory.ValueType  # 15
        """Штраф"""
        LOAN: Transaction._TransactionCategory.ValueType  # 19
        """Займ"""

    class TransactionCategory(_TransactionCategory, metaclass=_TransactionCategoryEnumTypeWrapper):
        """Категории транзакции."""

    OTHERS: Transaction.TransactionCategory.ValueType  # 0
    """Прочее"""
    DEPOSIT: Transaction.TransactionCategory.ValueType  # 1
    """Ввод ДС"""
    WITHDRAW: Transaction.TransactionCategory.ValueType  # 2
    """Вывод ДС"""
    INCOME: Transaction.TransactionCategory.ValueType  # 5
    """Доход"""
    COMMISSION: Transaction.TransactionCategory.ValueType  # 7
    """Комиссия"""
    TAX: Transaction.TransactionCategory.ValueType  # 8
    """Налог"""
    INHERITANCE: Transaction.TransactionCategory.ValueType  # 9
    """Наследство"""
    TRANSFER: Transaction.TransactionCategory.ValueType  # 11
    """Перевод ДС"""
    CONTRACT_TERMINATION: Transaction.TransactionCategory.ValueType  # 12
    """Расторжение договора"""
    OUTCOMES: Transaction.TransactionCategory.ValueType  # 13
    """Расходы"""
    FINE: Transaction.TransactionCategory.ValueType  # 15
    """Штраф"""
    LOAN: Transaction.TransactionCategory.ValueType  # 19
    """Займ"""

    @_typing.final
    class Trade(_message.Message):
        """Объект заполняется для торговых типов транзакций"""

        DESCRIPTOR: _descriptor.Descriptor

        SIZE_FIELD_NUMBER: _builtins.int
        PRICE_FIELD_NUMBER: _builtins.int
        ACCRUED_INTEREST_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def size(self) -> _decimal_pb2.Decimal:
            """Количество в шт."""

        @_builtins.property
        def price(self) -> _decimal_pb2.Decimal:
            """Цена сделки за штуку. Цена исполнения/Размер премии по опциону. Это цена заключения, значение берется из сделки."""

        @_builtins.property
        def accrued_interest(self) -> _decimal_pb2.Decimal:
            """НКД. Заполнено если в сделке есть НКД"""

        def __init__(
            self,
            *,
            size: _decimal_pb2.Decimal | None = ...,
            price: _decimal_pb2.Decimal | None = ...,
            accrued_interest: _decimal_pb2.Decimal | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["accrued_interest", b"accrued_interest", "price", b"price", "size", b"size"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["accrued_interest", b"accrued_interest", "price", b"price", "size", b"size"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    ID_FIELD_NUMBER: _builtins.int
    CATEGORY_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    SYMBOL_FIELD_NUMBER: _builtins.int
    CHANGE_FIELD_NUMBER: _builtins.int
    TRADE_FIELD_NUMBER: _builtins.int
    TRANSACTION_CATEGORY_FIELD_NUMBER: _builtins.int
    TRANSACTION_NAME_FIELD_NUMBER: _builtins.int
    CHANGE_QTY_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    """Идентификатор транзакции"""
    @_builtins.property
    @_deprecated("""This field has been marked as deprecated using proto field options.""")
    def category(self) -> _builtins.str:
        """Тип транзакции из TransactionCategory"""

    @category.setter
    @_deprecated("""This field has been marked as deprecated using proto field options.""")
    def category(self, value: _builtins.str) -> None:
        """Тип транзакции из TransactionCategory"""

    symbol: _builtins.str
    """Символ инструмента"""
    transaction_category: Global___Transaction.TransactionCategory.ValueType
    """Категория транзакции из TransactionCategory."""
    transaction_name: _builtins.str
    """Наименование транзакции"""
    @_builtins.property
    def timestamp(self) -> _timestamp_pb2.Timestamp:
        """Метка времени"""

    @_builtins.property
    def change(self) -> _money_pb2.Money:
        """Изменение в деньгах"""

    @_builtins.property
    def trade(self) -> Global___Transaction.Trade:
        """Информация о сделке"""

    @_builtins.property
    def change_qty(self) -> _decimal_pb2.Decimal:
        """Изменение в штуках, только для трансфера бумаг (для TransactionCategory = TRANSFER)"""

    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        category: _builtins.str = ...,
        timestamp: _timestamp_pb2.Timestamp | None = ...,
        symbol: _builtins.str = ...,
        change: _money_pb2.Money | None = ...,
        trade: Global___Transaction.Trade | None = ...,
        transaction_category: Global___Transaction.TransactionCategory.ValueType = ...,
        transaction_name: _builtins.str = ...,
        change_qty: _decimal_pb2.Decimal | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["change", b"change", "change_qty", b"change_qty", "timestamp", b"timestamp", "trade", b"trade"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["category", b"category", "change", b"change", "change_qty", b"change_qty", "id", b"id", "symbol", b"symbol", "timestamp", b"timestamp", "trade", b"trade", "transaction_category", b"transaction_category", "transaction_name", b"transaction_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Transaction: _TypeAlias = Transaction  # noqa: Y015
