"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from FinamPy.grpc import side_pb2 as _side_pb2
from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.type import decimal_pb2 as _decimal_pb2
from google.type import interval_pb2 as _interval_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _TimeFrame:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _TimeFrameEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_TimeFrame.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    TIME_FRAME_UNSPECIFIED: _TimeFrame.ValueType  # 0
    """Таймфрейм не указан"""
    TIME_FRAME_M1: _TimeFrame.ValueType  # 1
    """1 минута. Глубина данных 7 дней."""
    TIME_FRAME_M5: _TimeFrame.ValueType  # 5
    """5 минут. Глубина данных 30 дней."""
    TIME_FRAME_M15: _TimeFrame.ValueType  # 9
    """15 минут. Глубина данных 30 дней."""
    TIME_FRAME_M30: _TimeFrame.ValueType  # 11
    """30 минут. Глубина данных 30 дней."""
    TIME_FRAME_H1: _TimeFrame.ValueType  # 12
    """1 час. Глубина данных 30 дней."""
    TIME_FRAME_H2: _TimeFrame.ValueType  # 13
    """2 часа. Глубина данных 30 дней."""
    TIME_FRAME_H4: _TimeFrame.ValueType  # 15
    """4 часа. Глубина данных 30 дней."""
    TIME_FRAME_H8: _TimeFrame.ValueType  # 17
    """8 часов. Глубина данных 30 дней."""
    TIME_FRAME_D: _TimeFrame.ValueType  # 19
    """День. Глубина данных 365 дней."""
    TIME_FRAME_W: _TimeFrame.ValueType  # 20
    """Неделя. Глубина данных 365*5 дней."""
    TIME_FRAME_MN: _TimeFrame.ValueType  # 21
    """Месяц. Глубина данных 365*5 дней."""
    TIME_FRAME_QR: _TimeFrame.ValueType  # 22
    """Квартал. Глубина данных 365*5 дней."""

class TimeFrame(_TimeFrame, metaclass=_TimeFrameEnumTypeWrapper):
    """Доступные таймфреймы для свечей"""

TIME_FRAME_UNSPECIFIED: TimeFrame.ValueType  # 0
"""Таймфрейм не указан"""
TIME_FRAME_M1: TimeFrame.ValueType  # 1
"""1 минута. Глубина данных 7 дней."""
TIME_FRAME_M5: TimeFrame.ValueType  # 5
"""5 минут. Глубина данных 30 дней."""
TIME_FRAME_M15: TimeFrame.ValueType  # 9
"""15 минут. Глубина данных 30 дней."""
TIME_FRAME_M30: TimeFrame.ValueType  # 11
"""30 минут. Глубина данных 30 дней."""
TIME_FRAME_H1: TimeFrame.ValueType  # 12
"""1 час. Глубина данных 30 дней."""
TIME_FRAME_H2: TimeFrame.ValueType  # 13
"""2 часа. Глубина данных 30 дней."""
TIME_FRAME_H4: TimeFrame.ValueType  # 15
"""4 часа. Глубина данных 30 дней."""
TIME_FRAME_H8: TimeFrame.ValueType  # 17
"""8 часов. Глубина данных 30 дней."""
TIME_FRAME_D: TimeFrame.ValueType  # 19
"""День. Глубина данных 365 дней."""
TIME_FRAME_W: TimeFrame.ValueType  # 20
"""Неделя. Глубина данных 365*5 дней."""
TIME_FRAME_MN: TimeFrame.ValueType  # 21
"""Месяц. Глубина данных 365*5 дней."""
TIME_FRAME_QR: TimeFrame.ValueType  # 22
"""Квартал. Глубина данных 365*5 дней."""
Global___TimeFrame: _TypeAlias = TimeFrame  # noqa: Y015

@_typing.final
class BarsRequest(_message.Message):
    """Запрос получения исторических данных по инструменту (агрегированные свечи)"""

    DESCRIPTOR: _descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: _builtins.int
    TIMEFRAME_FIELD_NUMBER: _builtins.int
    INTERVAL_FIELD_NUMBER: _builtins.int
    symbol: _builtins.str
    """Символ инструмента"""
    timeframe: Global___TimeFrame.ValueType
    """Необходимый таймфрейм"""
    @_builtins.property
    def interval(self) -> _interval_pb2.Interval:
        """Начало и окончание запрашиваемого периода"""

    def __init__(
        self,
        *,
        symbol: _builtins.str = ...,
        timeframe: Global___TimeFrame.ValueType = ...,
        interval: _interval_pb2.Interval | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["interval", b"interval"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["interval", b"interval", "symbol", b"symbol", "timeframe", b"timeframe"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___BarsRequest: _TypeAlias = BarsRequest  # noqa: Y015

@_typing.final
class BarsResponse(_message.Message):
    """Список агрегированных свеч"""

    DESCRIPTOR: _descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: _builtins.int
    BARS_FIELD_NUMBER: _builtins.int
    symbol: _builtins.str
    """Символ инструмента"""
    @_builtins.property
    def bars(self) -> _containers.RepeatedCompositeFieldContainer[Global___Bar]:
        """Агрегированная свеча"""

    def __init__(
        self,
        *,
        symbol: _builtins.str = ...,
        bars: _abc.Iterable[Global___Bar] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bars", b"bars", "symbol", b"symbol"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___BarsResponse: _TypeAlias = BarsResponse  # noqa: Y015

@_typing.final
class QuoteRequest(_message.Message):
    """Запрос получения последней котировки по инструменту"""

    DESCRIPTOR: _descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: _builtins.int
    symbol: _builtins.str
    """Символ инструмента"""
    def __init__(
        self,
        *,
        symbol: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["symbol", b"symbol"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___QuoteRequest: _TypeAlias = QuoteRequest  # noqa: Y015

@_typing.final
class QuoteResponse(_message.Message):
    """Последняя котировка по инструменту"""

    DESCRIPTOR: _descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: _builtins.int
    QUOTE_FIELD_NUMBER: _builtins.int
    symbol: _builtins.str
    """Символ инструмента"""
    @_builtins.property
    def quote(self) -> Global___Quote:
        """Цена последней сделки"""

    def __init__(
        self,
        *,
        symbol: _builtins.str = ...,
        quote: Global___Quote | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["quote", b"quote"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["quote", b"quote", "symbol", b"symbol"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___QuoteResponse: _TypeAlias = QuoteResponse  # noqa: Y015

@_typing.final
class OrderBookRequest(_message.Message):
    """Запрос получения текущего стакана по инструменту"""

    DESCRIPTOR: _descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: _builtins.int
    symbol: _builtins.str
    """Символ инструмента"""
    def __init__(
        self,
        *,
        symbol: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["symbol", b"symbol"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___OrderBookRequest: _TypeAlias = OrderBookRequest  # noqa: Y015

@_typing.final
class OrderBookResponse(_message.Message):
    """Текущий стакан по инструменту"""

    DESCRIPTOR: _descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: _builtins.int
    ORDERBOOK_FIELD_NUMBER: _builtins.int
    symbol: _builtins.str
    """Символ инструмента"""
    @_builtins.property
    def orderbook(self) -> Global___OrderBook:
        """Стакан"""

    def __init__(
        self,
        *,
        symbol: _builtins.str = ...,
        orderbook: Global___OrderBook | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["orderbook", b"orderbook"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["orderbook", b"orderbook", "symbol", b"symbol"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___OrderBookResponse: _TypeAlias = OrderBookResponse  # noqa: Y015

@_typing.final
class LatestTradesRequest(_message.Message):
    """Запрос списка последних сделок по инструменту"""

    DESCRIPTOR: _descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: _builtins.int
    symbol: _builtins.str
    """Символ инструмента"""
    def __init__(
        self,
        *,
        symbol: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["symbol", b"symbol"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LatestTradesRequest: _TypeAlias = LatestTradesRequest  # noqa: Y015

@_typing.final
class LatestTradesResponse(_message.Message):
    """Список последних сделок по инструменту"""

    DESCRIPTOR: _descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: _builtins.int
    TRADES_FIELD_NUMBER: _builtins.int
    symbol: _builtins.str
    """Символ инструмента"""
    @_builtins.property
    def trades(self) -> _containers.RepeatedCompositeFieldContainer[Global___Trade]:
        """Список последних сделок"""

    def __init__(
        self,
        *,
        symbol: _builtins.str = ...,
        trades: _abc.Iterable[Global___Trade] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["symbol", b"symbol", "trades", b"trades"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LatestTradesResponse: _TypeAlias = LatestTradesResponse  # noqa: Y015

@_typing.final
class SubscribeQuoteRequest(_message.Message):
    """Запрос подписки на котировки по инструменту. Стрим"""

    DESCRIPTOR: _descriptor.Descriptor

    SYMBOLS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def symbols(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Список символов инструментов"""

    def __init__(
        self,
        *,
        symbols: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["symbols", b"symbols"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SubscribeQuoteRequest: _TypeAlias = SubscribeQuoteRequest  # noqa: Y015

@_typing.final
class SubscribeQuoteResponse(_message.Message):
    """Котировки по инструменту. Стрим"""

    DESCRIPTOR: _descriptor.Descriptor

    QUOTE_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def quote(self) -> _containers.RepeatedCompositeFieldContainer[Global___Quote]:
        """Список котировок"""

    @_builtins.property
    def error(self) -> Global___StreamError:
        """Ошибка стрим сервиса"""

    def __init__(
        self,
        *,
        quote: _abc.Iterable[Global___Quote] | None = ...,
        error: Global___StreamError | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "quote", b"quote"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SubscribeQuoteResponse: _TypeAlias = SubscribeQuoteResponse  # noqa: Y015

@_typing.final
class SubscribeOrderBookRequest(_message.Message):
    """Запрос подписки на стакан по инструменту. Стрим"""

    DESCRIPTOR: _descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: _builtins.int
    symbol: _builtins.str
    """Символ инструмента"""
    def __init__(
        self,
        *,
        symbol: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["symbol", b"symbol"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SubscribeOrderBookRequest: _TypeAlias = SubscribeOrderBookRequest  # noqa: Y015

@_typing.final
class SubscribeOrderBookResponse(_message.Message):
    """Стакан по инструменту. Стрим"""

    DESCRIPTOR: _descriptor.Descriptor

    ORDER_BOOK_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def order_book(self) -> _containers.RepeatedCompositeFieldContainer[Global___StreamOrderBook]:
        """Список стакан стримов"""

    def __init__(
        self,
        *,
        order_book: _abc.Iterable[Global___StreamOrderBook] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["order_book", b"order_book"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SubscribeOrderBookResponse: _TypeAlias = SubscribeOrderBookResponse  # noqa: Y015

@_typing.final
class SubscribeBarsRequest(_message.Message):
    """Запрос подписки на агрегированные свечи. Стрим"""

    DESCRIPTOR: _descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: _builtins.int
    TIMEFRAME_FIELD_NUMBER: _builtins.int
    symbol: _builtins.str
    """Символ инструмента"""
    timeframe: Global___TimeFrame.ValueType
    """Необходимый таймфрейм"""
    def __init__(
        self,
        *,
        symbol: _builtins.str = ...,
        timeframe: Global___TimeFrame.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["symbol", b"symbol", "timeframe", b"timeframe"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SubscribeBarsRequest: _TypeAlias = SubscribeBarsRequest  # noqa: Y015

@_typing.final
class SubscribeBarsResponse(_message.Message):
    """Список агрегированных свеч. Стрим"""

    DESCRIPTOR: _descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: _builtins.int
    BARS_FIELD_NUMBER: _builtins.int
    symbol: _builtins.str
    """Символ инструмента"""
    @_builtins.property
    def bars(self) -> _containers.RepeatedCompositeFieldContainer[Global___Bar]:
        """Агрегированная свеча"""

    def __init__(
        self,
        *,
        symbol: _builtins.str = ...,
        bars: _abc.Iterable[Global___Bar] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bars", b"bars", "symbol", b"symbol"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SubscribeBarsResponse: _TypeAlias = SubscribeBarsResponse  # noqa: Y015

@_typing.final
class Bar(_message.Message):
    """Информация об агрегированной свече"""

    DESCRIPTOR: _descriptor.Descriptor

    TIMESTAMP_FIELD_NUMBER: _builtins.int
    OPEN_FIELD_NUMBER: _builtins.int
    HIGH_FIELD_NUMBER: _builtins.int
    LOW_FIELD_NUMBER: _builtins.int
    CLOSE_FIELD_NUMBER: _builtins.int
    VOLUME_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def timestamp(self) -> _timestamp_pb2.Timestamp:
        """Метка времени"""

    @_builtins.property
    def open(self) -> _decimal_pb2.Decimal:
        """Цена открытия свечи"""

    @_builtins.property
    def high(self) -> _decimal_pb2.Decimal:
        """Максимальная цена свечи"""

    @_builtins.property
    def low(self) -> _decimal_pb2.Decimal:
        """Минимальная цена свечи"""

    @_builtins.property
    def close(self) -> _decimal_pb2.Decimal:
        """Цена закрытия свечи"""

    @_builtins.property
    def volume(self) -> _decimal_pb2.Decimal:
        """Объём торгов за свечу в шт."""

    def __init__(
        self,
        *,
        timestamp: _timestamp_pb2.Timestamp | None = ...,
        open: _decimal_pb2.Decimal | None = ...,
        high: _decimal_pb2.Decimal | None = ...,
        low: _decimal_pb2.Decimal | None = ...,
        close: _decimal_pb2.Decimal | None = ...,
        volume: _decimal_pb2.Decimal | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["close", b"close", "high", b"high", "low", b"low", "open", b"open", "timestamp", b"timestamp", "volume", b"volume"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["close", b"close", "high", b"high", "low", b"low", "open", b"open", "timestamp", b"timestamp", "volume", b"volume"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Bar: _TypeAlias = Bar  # noqa: Y015

@_typing.final
class Quote(_message.Message):
    """Информация о котировке"""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Option(_message.Message):
        """Информация об опционе"""

        DESCRIPTOR: _descriptor.Descriptor

        OPEN_INTEREST_FIELD_NUMBER: _builtins.int
        IMPLIED_VOLATILITY_FIELD_NUMBER: _builtins.int
        THEORETICAL_PRICE_FIELD_NUMBER: _builtins.int
        DELTA_FIELD_NUMBER: _builtins.int
        GAMMA_FIELD_NUMBER: _builtins.int
        THETA_FIELD_NUMBER: _builtins.int
        VEGA_FIELD_NUMBER: _builtins.int
        RHO_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def open_interest(self) -> _decimal_pb2.Decimal:
            """Открытый интерес"""

        @_builtins.property
        def implied_volatility(self) -> _decimal_pb2.Decimal:
            """Подразумеваемая волатильность"""

        @_builtins.property
        def theoretical_price(self) -> _decimal_pb2.Decimal:
            """Теоретическая цена"""

        @_builtins.property
        def delta(self) -> _decimal_pb2.Decimal:
            """Delta"""

        @_builtins.property
        def gamma(self) -> _decimal_pb2.Decimal:
            """Gamma"""

        @_builtins.property
        def theta(self) -> _decimal_pb2.Decimal:
            """Theta"""

        @_builtins.property
        def vega(self) -> _decimal_pb2.Decimal:
            """Vega"""

        @_builtins.property
        def rho(self) -> _decimal_pb2.Decimal:
            """Rho"""

        def __init__(
            self,
            *,
            open_interest: _decimal_pb2.Decimal | None = ...,
            implied_volatility: _decimal_pb2.Decimal | None = ...,
            theoretical_price: _decimal_pb2.Decimal | None = ...,
            delta: _decimal_pb2.Decimal | None = ...,
            gamma: _decimal_pb2.Decimal | None = ...,
            theta: _decimal_pb2.Decimal | None = ...,
            vega: _decimal_pb2.Decimal | None = ...,
            rho: _decimal_pb2.Decimal | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["delta", b"delta", "gamma", b"gamma", "implied_volatility", b"implied_volatility", "open_interest", b"open_interest", "rho", b"rho", "theoretical_price", b"theoretical_price", "theta", b"theta", "vega", b"vega"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["delta", b"delta", "gamma", b"gamma", "implied_volatility", b"implied_volatility", "open_interest", b"open_interest", "rho", b"rho", "theoretical_price", b"theoretical_price", "theta", b"theta", "vega", b"vega"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    SYMBOL_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    ASK_FIELD_NUMBER: _builtins.int
    ASK_SIZE_FIELD_NUMBER: _builtins.int
    BID_FIELD_NUMBER: _builtins.int
    BID_SIZE_FIELD_NUMBER: _builtins.int
    LAST_FIELD_NUMBER: _builtins.int
    LAST_SIZE_FIELD_NUMBER: _builtins.int
    VOLUME_FIELD_NUMBER: _builtins.int
    TURNOVER_FIELD_NUMBER: _builtins.int
    OPEN_FIELD_NUMBER: _builtins.int
    HIGH_FIELD_NUMBER: _builtins.int
    LOW_FIELD_NUMBER: _builtins.int
    CLOSE_FIELD_NUMBER: _builtins.int
    CHANGE_FIELD_NUMBER: _builtins.int
    OPTION_FIELD_NUMBER: _builtins.int
    symbol: _builtins.str
    """Символ инструмента"""
    @_builtins.property
    def timestamp(self) -> _timestamp_pb2.Timestamp:
        """Метка времени"""

    @_builtins.property
    def ask(self) -> _decimal_pb2.Decimal:
        """Аск. 0 при отсутствии активного аска"""

    @_builtins.property
    def ask_size(self) -> _decimal_pb2.Decimal:
        """Размер аска"""

    @_builtins.property
    def bid(self) -> _decimal_pb2.Decimal:
        """Бид. 0 при отсутствии активного бида"""

    @_builtins.property
    def bid_size(self) -> _decimal_pb2.Decimal:
        """Размер бида"""

    @_builtins.property
    def last(self) -> _decimal_pb2.Decimal:
        """Цена последней сделки"""

    @_builtins.property
    def last_size(self) -> _decimal_pb2.Decimal:
        """Размер последней сделки"""

    @_builtins.property
    def volume(self) -> _decimal_pb2.Decimal:
        """Дневной объем сделок"""

    @_builtins.property
    def turnover(self) -> _decimal_pb2.Decimal:
        """Дневной оборот сделок"""

    @_builtins.property
    def open(self) -> _decimal_pb2.Decimal:
        """Цена открытия. Дневная"""

    @_builtins.property
    def high(self) -> _decimal_pb2.Decimal:
        """Максимальная цена. Дневная"""

    @_builtins.property
    def low(self) -> _decimal_pb2.Decimal:
        """Минимальная цена. Дневная"""

    @_builtins.property
    def close(self) -> _decimal_pb2.Decimal:
        """Цена закрытия. Дневная"""

    @_builtins.property
    def change(self) -> _decimal_pb2.Decimal:
        """Изменение цены (last минус close)"""

    @_builtins.property
    def option(self) -> Global___Quote.Option:
        """Информация об опционе"""

    def __init__(
        self,
        *,
        symbol: _builtins.str = ...,
        timestamp: _timestamp_pb2.Timestamp | None = ...,
        ask: _decimal_pb2.Decimal | None = ...,
        ask_size: _decimal_pb2.Decimal | None = ...,
        bid: _decimal_pb2.Decimal | None = ...,
        bid_size: _decimal_pb2.Decimal | None = ...,
        last: _decimal_pb2.Decimal | None = ...,
        last_size: _decimal_pb2.Decimal | None = ...,
        volume: _decimal_pb2.Decimal | None = ...,
        turnover: _decimal_pb2.Decimal | None = ...,
        open: _decimal_pb2.Decimal | None = ...,
        high: _decimal_pb2.Decimal | None = ...,
        low: _decimal_pb2.Decimal | None = ...,
        close: _decimal_pb2.Decimal | None = ...,
        change: _decimal_pb2.Decimal | None = ...,
        option: Global___Quote.Option | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["additions", b"additions", "ask", b"ask", "ask_size", b"ask_size", "bid", b"bid", "bid_size", b"bid_size", "change", b"change", "close", b"close", "high", b"high", "last", b"last", "last_size", b"last_size", "low", b"low", "open", b"open", "option", b"option", "timestamp", b"timestamp", "turnover", b"turnover", "volume", b"volume"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["additions", b"additions", "ask", b"ask", "ask_size", b"ask_size", "bid", b"bid", "bid_size", b"bid_size", "change", b"change", "close", b"close", "high", b"high", "last", b"last", "last_size", b"last_size", "low", b"low", "open", b"open", "option", b"option", "symbol", b"symbol", "timestamp", b"timestamp", "turnover", b"turnover", "volume", b"volume"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_additions: _TypeAlias = _typing.Literal["option"]  # noqa: Y015
    _WhichOneofArgType_additions: _TypeAlias = _typing.Literal["additions", b"additions"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_additions) -> _WhichOneofReturnType_additions | None: ...

Global___Quote: _TypeAlias = Quote  # noqa: Y015

@_typing.final
class OrderBook(_message.Message):
    """Информация о стакане"""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Row(_message.Message):
        """Информация об уровне в стакане (строке)"""

        DESCRIPTOR: _descriptor.Descriptor

        class _Action:
            ValueType = _typing.NewType("ValueType", _builtins.int)
            V: _TypeAlias = ValueType  # noqa: Y015

        class _ActionEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[OrderBook.Row._Action.ValueType], _builtins.type):
            DESCRIPTOR: _descriptor.EnumDescriptor
            ACTION_UNSPECIFIED: OrderBook.Row._Action.ValueType  # 0
            """Действие не указано"""
            ACTION_REMOVE: OrderBook.Row._Action.ValueType  # 1
            """Удалить"""
            ACTION_ADD: OrderBook.Row._Action.ValueType  # 2
            """Добавить"""
            ACTION_UPDATE: OrderBook.Row._Action.ValueType  # 3
            """Обновить"""

        class Action(_Action, metaclass=_ActionEnumTypeWrapper):
            """Команда"""

        ACTION_UNSPECIFIED: OrderBook.Row.Action.ValueType  # 0
        """Действие не указано"""
        ACTION_REMOVE: OrderBook.Row.Action.ValueType  # 1
        """Удалить"""
        ACTION_ADD: OrderBook.Row.Action.ValueType  # 2
        """Добавить"""
        ACTION_UPDATE: OrderBook.Row.Action.ValueType  # 3
        """Обновить"""

        PRICE_FIELD_NUMBER: _builtins.int
        SELL_SIZE_FIELD_NUMBER: _builtins.int
        BUY_SIZE_FIELD_NUMBER: _builtins.int
        ACTION_FIELD_NUMBER: _builtins.int
        MPID_FIELD_NUMBER: _builtins.int
        TIMESTAMP_FIELD_NUMBER: _builtins.int
        action: Global___OrderBook.Row.Action.ValueType
        """Команда"""
        mpid: _builtins.str
        """Идентификатор участника рынка"""
        @_builtins.property
        def price(self) -> _decimal_pb2.Decimal:
            """Цена"""

        @_builtins.property
        def sell_size(self) -> _decimal_pb2.Decimal:
            """Размер на продажу"""

        @_builtins.property
        def buy_size(self) -> _decimal_pb2.Decimal:
            """Размер на покупку"""

        @_builtins.property
        def timestamp(self) -> _timestamp_pb2.Timestamp:
            """Метка времени"""

        def __init__(
            self,
            *,
            price: _decimal_pb2.Decimal | None = ...,
            sell_size: _decimal_pb2.Decimal | None = ...,
            buy_size: _decimal_pb2.Decimal | None = ...,
            action: Global___OrderBook.Row.Action.ValueType = ...,
            mpid: _builtins.str = ...,
            timestamp: _timestamp_pb2.Timestamp | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["buy_size", b"buy_size", "price", b"price", "sell_size", b"sell_size", "side", b"side", "timestamp", b"timestamp"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["action", b"action", "buy_size", b"buy_size", "mpid", b"mpid", "price", b"price", "sell_size", b"sell_size", "side", b"side", "timestamp", b"timestamp"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_side: _TypeAlias = _typing.Literal["sell_size", "buy_size"]  # noqa: Y015
        _WhichOneofArgType_side: _TypeAlias = _typing.Literal["side", b"side"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType_side) -> _WhichOneofReturnType_side | None: ...

    ROWS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def rows(self) -> _containers.RepeatedCompositeFieldContainer[Global___OrderBook.Row]:
        """Уровни стакана"""

    def __init__(
        self,
        *,
        rows: _abc.Iterable[Global___OrderBook.Row] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["rows", b"rows"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___OrderBook: _TypeAlias = OrderBook  # noqa: Y015

@_typing.final
class Trade(_message.Message):
    """Информация о сделке"""

    DESCRIPTOR: _descriptor.Descriptor

    TRADE_ID_FIELD_NUMBER: _builtins.int
    MPID_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    PRICE_FIELD_NUMBER: _builtins.int
    SIZE_FIELD_NUMBER: _builtins.int
    SIDE_FIELD_NUMBER: _builtins.int
    trade_id: _builtins.str
    """Идентификатор сделки, отправленный биржей"""
    mpid: _builtins.str
    """Идентификатор участника рынка"""
    side: _side_pb2.Side.ValueType
    """ Сторона сделки (buy или sell)"""
    @_builtins.property
    def timestamp(self) -> _timestamp_pb2.Timestamp:
        """Метка времени"""

    @_builtins.property
    def price(self) -> _decimal_pb2.Decimal:
        """Цена сделки"""

    @_builtins.property
    def size(self) -> _decimal_pb2.Decimal:
        """Размер сделки"""

    def __init__(
        self,
        *,
        trade_id: _builtins.str = ...,
        mpid: _builtins.str = ...,
        timestamp: _timestamp_pb2.Timestamp | None = ...,
        price: _decimal_pb2.Decimal | None = ...,
        size: _decimal_pb2.Decimal | None = ...,
        side: _side_pb2.Side.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["price", b"price", "size", b"size", "timestamp", b"timestamp"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["mpid", b"mpid", "price", b"price", "side", b"side", "size", b"size", "timestamp", b"timestamp", "trade_id", b"trade_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Trade: _TypeAlias = Trade  # noqa: Y015

@_typing.final
class StreamError(_message.Message):
    """Ошибка стрим сервиса"""

    DESCRIPTOR: _descriptor.Descriptor

    CODE_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    code: _builtins.int
    """Код ошибки"""
    description: _builtins.str
    """Описание ошибки"""
    def __init__(
        self,
        *,
        code: _builtins.int = ...,
        description: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["code", b"code", "description", b"description"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StreamError: _TypeAlias = StreamError  # noqa: Y015

@_typing.final
class StreamOrderBook(_message.Message):
    """Стакан по инструменту. Стрим"""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Row(_message.Message):
        """Информация об уровне в стакане (строке)"""

        DESCRIPTOR: _descriptor.Descriptor

        class _Action:
            ValueType = _typing.NewType("ValueType", _builtins.int)
            V: _TypeAlias = ValueType  # noqa: Y015

        class _ActionEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[StreamOrderBook.Row._Action.ValueType], _builtins.type):
            DESCRIPTOR: _descriptor.EnumDescriptor
            ACTION_UNSPECIFIED: StreamOrderBook.Row._Action.ValueType  # 0
            """Действие не указано"""
            ACTION_REMOVE: StreamOrderBook.Row._Action.ValueType  # 1
            """Удалить"""
            ACTION_ADD: StreamOrderBook.Row._Action.ValueType  # 2
            """Добавить"""
            ACTION_UPDATE: StreamOrderBook.Row._Action.ValueType  # 3
            """Обновить"""

        class Action(_Action, metaclass=_ActionEnumTypeWrapper):
            """Команда"""

        ACTION_UNSPECIFIED: StreamOrderBook.Row.Action.ValueType  # 0
        """Действие не указано"""
        ACTION_REMOVE: StreamOrderBook.Row.Action.ValueType  # 1
        """Удалить"""
        ACTION_ADD: StreamOrderBook.Row.Action.ValueType  # 2
        """Добавить"""
        ACTION_UPDATE: StreamOrderBook.Row.Action.ValueType  # 3
        """Обновить"""

        PRICE_FIELD_NUMBER: _builtins.int
        SELL_SIZE_FIELD_NUMBER: _builtins.int
        BUY_SIZE_FIELD_NUMBER: _builtins.int
        ACTION_FIELD_NUMBER: _builtins.int
        MPID_FIELD_NUMBER: _builtins.int
        TIMESTAMP_FIELD_NUMBER: _builtins.int
        action: Global___StreamOrderBook.Row.Action.ValueType
        """Команда"""
        mpid: _builtins.str
        """Идентификатор участника рынка"""
        @_builtins.property
        def price(self) -> _decimal_pb2.Decimal:
            """Цена"""

        @_builtins.property
        def sell_size(self) -> _decimal_pb2.Decimal:
            """Размер на продажу"""

        @_builtins.property
        def buy_size(self) -> _decimal_pb2.Decimal:
            """Размер на покупку"""

        @_builtins.property
        def timestamp(self) -> _timestamp_pb2.Timestamp:
            """Метка времени"""

        def __init__(
            self,
            *,
            price: _decimal_pb2.Decimal | None = ...,
            sell_size: _decimal_pb2.Decimal | None = ...,
            buy_size: _decimal_pb2.Decimal | None = ...,
            action: Global___StreamOrderBook.Row.Action.ValueType = ...,
            mpid: _builtins.str = ...,
            timestamp: _timestamp_pb2.Timestamp | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["buy_size", b"buy_size", "price", b"price", "sell_size", b"sell_size", "side", b"side", "timestamp", b"timestamp"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["action", b"action", "buy_size", b"buy_size", "mpid", b"mpid", "price", b"price", "sell_size", b"sell_size", "side", b"side", "timestamp", b"timestamp"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_side: _TypeAlias = _typing.Literal["sell_size", "buy_size"]  # noqa: Y015
        _WhichOneofArgType_side: _TypeAlias = _typing.Literal["side", b"side"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType_side) -> _WhichOneofReturnType_side | None: ...

    SYMBOL_FIELD_NUMBER: _builtins.int
    ROWS_FIELD_NUMBER: _builtins.int
    symbol: _builtins.str
    """Символ инструмента"""
    @_builtins.property
    def rows(self) -> _containers.RepeatedCompositeFieldContainer[Global___StreamOrderBook.Row]:
        """Уровни стакана"""

    def __init__(
        self,
        *,
        symbol: _builtins.str = ...,
        rows: _abc.Iterable[Global___StreamOrderBook.Row] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["rows", b"rows", "symbol", b"symbol"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StreamOrderBook: _TypeAlias = StreamOrderBook  # noqa: Y015

@_typing.final
class SubscribeLatestTradesRequest(_message.Message):
    """Запрос списка последних сделок по инструменту. Стрим"""

    DESCRIPTOR: _descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: _builtins.int
    symbol: _builtins.str
    """Символ инструмента"""
    def __init__(
        self,
        *,
        symbol: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["symbol", b"symbol"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SubscribeLatestTradesRequest: _TypeAlias = SubscribeLatestTradesRequest  # noqa: Y015

@_typing.final
class SubscribeLatestTradesResponse(_message.Message):
    """Список последних сделок по инструменту. Стрим"""

    DESCRIPTOR: _descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: _builtins.int
    TRADES_FIELD_NUMBER: _builtins.int
    symbol: _builtins.str
    """Символ инструмента"""
    @_builtins.property
    def trades(self) -> _containers.RepeatedCompositeFieldContainer[Global___Trade]:
        """Список сделок"""

    def __init__(
        self,
        *,
        symbol: _builtins.str = ...,
        trades: _abc.Iterable[Global___Trade] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["symbol", b"symbol", "trades", b"trades"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SubscribeLatestTradesResponse: _TypeAlias = SubscribeLatestTradesResponse  # noqa: Y015
